/-
Copyright (c) 2026 Jon Bannon. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Bannon, Michael R. Douglas
-/

module

public import SpectralTriples.FinitelySummable
public import SpectralTriples.DiagonalOperator
public import Mathlib.Algebra.Star.Subalgebra
public import Mathlib.Analysis.InnerProductSpace.l2Space

/-! # The Dirac spectral triple of the circle `S¹`

The simplest concrete (odd, finitely summable) spectral triple, built on the Fourier side so
that the Dirac operator is **diagonal**, bypassing spin bundles and Sobolev theory.

* `H = ℓ²(ℤ)` (`lp (fun _ : ℤ => ℂ) 2`), the Fourier model of `L²(S¹)` with orthonormal
  basis `(eₙ)_{n∈ℤ}`.
* `D = -i d/dθ`, acting diagonally as `eₙ ↦ n · eₙ`, with maximal domain
  `dom D = { a ∈ ℓ²(ℤ) : Σ n² |aₙ|² < ∞ }` (the `H¹` Sobolev space).
* `π : C^∞(S¹) → 𝓑(ℓ²(ℤ))` by Fourier convolution; `[D, π(f)] = π(-i f')` is bounded.

`D` is self-adjoint with **compact resolvent** (`(i·1 − D)⁻¹` is diagonal with eigenvalues
`1/(i − n) → 0`), and the algebra `π : ℂ[W] → 𝓑(ℓ²(ℤ))` generated by the single Fourier shift
unitary `W 1` (the analogue of multiplication by `e^{iθ}`) gives a faithful representation
with bounded commutator, so the whole data assembles into a **finitely summable spectral
triple** via `IsOddSpectralTriple.toIsFinitelySummableSpectralTriple`.

## Construction status and plan

All steps are complete: the space, the `H¹` domain, the **diagonal Dirac operator**
(`diracDirac`), its **self-adjointness** (hence `i ∈ ρ(D)`), **compact resolvent**, the
**representation** of the shift algebra, and the **assembly** as an odd, finitely-summable
spectral triple.

1. **Diagonal operator** — done (`diracDirac`, with `diracDirac_apply : (D a)ₙ = n · aₙ`).
2. **Self-adjointness** — done (`diracDirac_isSelfAdjoint`): symmetry from `inner_eq_tsum` +
   reality of the eigenvalues, then the adjoint-domain inclusion by testing against
   `lp.single 2 n 1` to read off `(D† b)ₙ = n · bₙ`. Gives `i ∈ ρ(D)` (`mem_resolventSet_I`).
3. **Compact resolvent** — done (`isCompactOperator_resolvent_I`): the resolvent is the
   bounded diagonal operator `bₙ ↦ bₙ/(i − n)`, a norm limit of finite-rank truncations since
   `1/(i − n) → 0`, via `lpDiag.isCompactOperator_diagL`.
4. **Representation** `rep : algebra →⋆ₐ[ℂ] 𝓑(L2)` — done: `algebra` is the star-subalgebra
   generated by the shift unitary `W 1` (the Fourier image of the trigonometric polynomials
   `ℂ[ℤ]` on `S¹`), and `rep` is the inclusion. The shift preserves the `H¹` domain and has
   bounded commutator `[D, W g] = -g • W g` (the eigenvalues are additive in the shift, so the
   commutator collapses to a scalar multiple of `W g` itself); this propagates to all of
   `algebra` by `StarAlgebra.adjoin_induction`.
5. **Assemble** — done: `isOddSpectralTriple`, and via `toIsFinitelySummableSpectralTriple`
   the finitely summable triple `isFinitelySummableSpectralTriple` at `i`.

See `IsSelfAdjoint.mem_resolventSet` (off-real-axis bijectivity) and
`IsSelfAdjoint.isClosed_range_subDirac` for the criterion this construction feeds.
-/

@[expose] public section

open LinearPMap
open Filter
open scoped Topology ENNReal

namespace SpectralTriples.Circle

/-- The Fourier model `ℓ²(ℤ)` of `L²(S¹)`: square-summable bi-infinite sequences of complex
numbers, a separable complex Hilbert space with orthonormal basis `(eₙ)_{n ∈ ℤ}`. -/
abbrev L2 : Type := lp (fun _ : ℤ => ℂ) 2

noncomputable instance : NormedAddCommGroup L2 := inferInstance
noncomputable instance : InnerProductSpace ℂ L2 := inferInstance
instance : CompleteSpace L2 := inferInstance

/-- The eigenvalues of the circle Dirac operator `D = -i d/dθ`: `D eₙ = n · eₙ`, so the `n`-th
eigenvalue is the real number `n`. These are real (hence `D` is symmetric) and satisfy
`|n| → ∞` (hence `D` has compact resolvent). -/
def diracEigen : ℤ → ℝ := fun n => (n : ℝ)

/-- The maximal domain of the circle Dirac operator: the `H¹` Sobolev space
`{ a ∈ ℓ²(ℤ) : Σ n² |aₙ|² < ∞ }`, i.e. those `a` for which `n ↦ n · aₙ` is again in `ℓ²(ℤ)`.
This is the domain on which the diagonal Dirac operator `(D a)ₙ = n · aₙ` will be defined. -/
def diracDomain : Submodule ℂ L2 where
  carrier := {a | Memℓp (fun n => (diracEigen n : ℂ) * a n) 2}
  zero_mem' := by
    simp only [Set.mem_setOf_eq, lp.coeFn_zero, Pi.zero_apply, mul_zero]
    exact zero_memℓp
  add_mem' := by
    intro a b ha hb
    simp only [Set.mem_setOf_eq, lp.coeFn_add, Pi.add_apply, mul_add] at *
    exact ha.add hb
  smul_mem' := by
    intro c a ha
    simp only [Set.mem_setOf_eq, lp.coeFn_smul, Pi.smul_apply, smul_eq_mul] at *
    have hrw : (fun n => (diracEigen n : ℂ) * (c * a n))
        = c • fun n => (diracEigen n : ℂ) * a n := by
      funext n; simp only [Pi.smul_apply, smul_eq_mul]; ring
    rw [hrw]; exact ha.const_smul c

theorem mem_diracDomain_iff (a : L2) :
    a ∈ diracDomain ↔ Memℓp (fun n => (diracEigen n : ℂ) * a n) 2 := Iff.rfl

/-- Coordinatewise multiplication by the eigenvalue sequence `(n)`, as an element of `ℓ²(ℤ)`,
given a proof that the result is square-summable. -/
def applyDirac (a : L2) (h : Memℓp (fun n => (diracEigen n : ℂ) * a n) 2) : L2 :=
  ⟨fun n => (diracEigen n : ℂ) * a n, h⟩

@[simp] theorem coe_applyDirac (a : L2) (h) (n : ℤ) :
    (applyDirac a h) n = (diracEigen n : ℂ) * a n := rfl

/-- The circle Dirac operator `D = -i d/dθ` as an unbounded `LinearPMap`: diagonal on the
Fourier basis, `(D a)ₙ = n · aₙ`, with domain the `H¹` Sobolev space `diracDomain`. -/
noncomputable def diracDirac : L2 →ₗ.[ℂ] L2 where
  domain := diracDomain
  toFun :=
    { toFun := fun a => applyDirac (a : L2) ((mem_diracDomain_iff _).mp a.2)
      map_add' := fun a b => by
        ext n
        simp only [coe_applyDirac, Submodule.coe_add, lp.coeFn_add, Pi.add_apply, mul_add]
      map_smul' := fun c a => by
        ext n
        simp only [coe_applyDirac, Submodule.coe_smul, lp.coeFn_smul, Pi.smul_apply,
          smul_eq_mul, RingHom.id_apply, mul_left_comm] }

@[simp] theorem diracDirac_apply (a : diracDomain) (n : ℤ) :
    (diracDirac a) n = (diracEigen n : ℂ) * (a : L2) n := rfl

/-- The circle Dirac operator is symmetric (formally self-adjoint): `⟪D x, y⟫ = ⟪x, D y⟫`
on its domain, because its eigenvalues are real. -/
theorem diracDirac_isFormalAdjoint : diracDirac.IsFormalAdjoint diracDirac := by
  intro x y
  rw [lp.inner_eq_tsum, lp.inner_eq_tsum]
  refine tsum_congr fun n => ?_
  simp only [diracDirac_apply, RCLike.inner_apply, map_mul, Complex.conj_ofReal]
  ring

/-- Each Fourier basis vector `eₙ = lp.single 2 n 1` lies in the `H¹` domain (it has finite
support, so `m ↦ m · (eₙ)ₘ = n · eₙ` is square-summable). -/
theorem single_mem_diracDomain (n : ℤ) : (lp.single 2 n (1 : ℂ) : L2) ∈ diracDomain := by
  rw [mem_diracDomain_iff]
  have hfun : (fun m => (diracEigen m : ℂ) * (lp.single 2 n (1 : ℂ) : L2) m)
      = (diracEigen n : ℂ) • (⇑(lp.single 2 n (1 : ℂ) : L2) : ℤ → ℂ) := by
    funext m
    rcases eq_or_ne m n with h | h
    · subst h; simp [lp.single_apply]
    · simp [lp.single_apply, h]
  rw [hfun]
  exact (lp.memℓp _).const_smul _

/-- The `H¹` domain is dense in `ℓ²(ℤ)`: it contains every Fourier basis vector, so its
orthogonal complement is trivial. -/
theorem dense_diracDomain : Dense (diracDirac.domain : Set L2) := by
  change Dense (diracDomain : Set L2)
  have horth : (diracDomain : Submodule ℂ L2)ᗮ = ⊥ := by
    rw [Submodule.eq_bot_iff]
    intro y hy
    refine lp.ext (funext fun n => ?_)
    have h0 : inner ℂ (lp.single 2 n (1 : ℂ) : L2) y = 0 := hy _ (single_mem_diracDomain n)
    rw [lp.inner_single_left] at h0
    simpa [RCLike.inner_apply, lp.coeFn_zero] using h0
  have htop : diracDomain.topologicalClosure = ⊤ :=
    (Submodule.topologicalClosure_eq_top_iff (K := diracDomain)).mpr horth
  rw [dense_iff_closure_eq, ← Submodule.topologicalClosure_coe, htop, Submodule.top_coe]

/-- The circle Dirac operator is contained in its adjoint (symmetry ⇒ `D ≤ D†`). -/
theorem diracDirac_le_adjoint : diracDirac ≤ diracDirac† :=
  diracDirac_isFormalAdjoint.le_adjoint dense_diracDomain

/-- **The circle Dirac operator is self-adjoint.** Since it is symmetric (so `D ≤ D†`), it
suffices that `D†.domain ⊆ D.domain`: for `y ∈ D†.domain`, testing the adjoint relation against
each Fourier basis vector `eₙ` gives `(D† y)ₙ = n · yₙ`, so `n ↦ n · yₙ` is square-summable and
`y` lies in the `H¹` domain. -/
theorem diracDirac_isSelfAdjoint : IsSelfAdjoint diracDirac := by
  rw [isSelfAdjoint_def]
  have hfa : diracDirac†.IsFormalAdjoint diracDirac := adjoint_isFormalAdjoint dense_diracDomain
  have hdomle : diracDirac†.domain ≤ diracDomain := by
    intro y hy
    rw [mem_diracDomain_iff]
    have hcoe : (fun n => (diracEigen n : ℂ) * y n) = ⇑(diracDirac† ⟨y, hy⟩) := by
      funext n
      have key := hfa ⟨y, hy⟩ ⟨lp.single 2 n (1 : ℂ), single_mem_diracDomain n⟩
      have hDe : diracDirac ⟨lp.single 2 n (1 : ℂ), single_mem_diracDomain n⟩
          = (diracEigen n : ℂ) • (lp.single 2 n (1 : ℂ) : L2) := by
        refine lp.ext (funext fun m => ?_)
        simp only [diracDirac_apply, lp.coeFn_smul, Pi.smul_apply, smul_eq_mul]
        rcases eq_or_ne m n with h | h
        · subst h; rfl
        · simp [lp.single_apply, h]
      rw [lp.inner_single_right, hDe, inner_smul_right, lp.inner_single_right] at key
      have key2 := congrArg (starRingEnd ℂ) key
      simp [RCLike.inner_apply, map_mul, Complex.conj_ofReal] at key2
      exact key2.symm
    rw [hcoe]; exact lp.memℓp _
  have heq : diracDirac.domain = diracDirac†.domain :=
    le_antisymm diracDirac_le_adjoint.1 hdomle
  exact (LinearPMap.eq_of_le_of_domain_eq diracDirac_le_adjoint heq).symm

/-- `i` lies in the resolvent set of the circle Dirac operator: it is self-adjoint and
`Im i = 1 ≠ 0`, so the basic criterion applies. -/
theorem mem_resolventSet_I : Complex.I ∈ diracDirac.resolventSet :=
  diracDirac_isSelfAdjoint.mem_resolventSet (by simp)

/-! ### Compact resolvent -/

/-- The resolvent block at Fourier mode `n`: scalar multiplication by `(i - n)⁻¹` on the
fibre `ℂ`. -/
private noncomputable def resolventBlock (n : ℤ) : ℂ →L[ℂ] ℂ :=
  (Complex.I - (diracEigen n : ℂ))⁻¹ • ContinuousLinearMap.id ℂ ℂ

private lemma norm_sub_eigen_ge_one (n : ℤ) : (1 : ℝ) ≤ ‖Complex.I - (diracEigen n : ℂ)‖ := by
  have him : RCLike.im (Complex.I - (diracEigen n : ℂ)) = 1 := by simp [diracEigen]
  have h := RCLike.abs_im_le_norm (Complex.I - (diracEigen n : ℂ))
  rwa [him, abs_one] at h

private lemma norm_resolventBlock_eq (n : ℤ) :
    ‖resolventBlock n‖ = (‖Complex.I - (diracEigen n : ℂ)‖)⁻¹ := by
  unfold resolventBlock
  rw [norm_smul, ContinuousLinearMap.norm_id, mul_one, norm_inv]

private lemma norm_resolventBlock_le_one (n : ℤ) : ‖resolventBlock n‖ ≤ 1 := by
  rw [norm_resolventBlock_eq]
  exact inv_le_one_of_one_le₀ (norm_sub_eigen_ge_one n)

private lemma norm_sub_eigen_tendsto_atTop :
    Tendsto (fun n : ℤ => ‖Complex.I - (diracEigen n : ℂ)‖) cofinite atTop := by
  have habs : Tendsto (fun n : ℤ => |(n : ℝ)|) cofinite atTop := by
    rw [Int.cofinite_eq, tendsto_sup]
    exact ⟨tendsto_abs_atBot_atTop.comp (tendsto_intCast_atBot_iff.2 tendsto_id),
      tendsto_abs_atTop_atTop.comp tendsto_intCast_atTop_atTop⟩
  refine tendsto_atTop_mono' _ ?_ habs
  filter_upwards with n
  have hre : RCLike.re (Complex.I - (diracEigen n : ℂ)) = -(diracEigen n : ℝ) := by
    simp [diracEigen]
  have h := RCLike.abs_re_le_norm (Complex.I - (diracEigen n : ℂ))
  rwa [hre, abs_neg] at h

private lemma norm_resolventBlock_tendsto_zero :
    Tendsto (fun n : ℤ => ‖resolventBlock n‖) cofinite (𝓝 0) := by
  simp_rw [norm_resolventBlock_eq]
  exact tendsto_inv_atTop_zero.comp norm_sub_eigen_tendsto_atTop

private noncomputable def resolventDiag : L2 →L[ℂ] L2 :=
  lpDiag.diagL (𝕜 := ℂ) (G := fun _ : ℤ => ℂ) resolventBlock zero_le_one
    norm_resolventBlock_le_one

private lemma isCompactOperator_resolventDiag : IsCompactOperator resolventDiag :=
  lpDiag.isCompactOperator_diagL (𝕜 := ℂ) (G := fun _ : ℤ => ℂ) resolventBlock zero_le_one
    norm_resolventBlock_le_one norm_resolventBlock_tendsto_zero

/-- The resolvent block inverts `i·1 − D` at Fourier mode `n`. -/
private lemma resolventBlock_left_inverse (n : ℤ) (v : ℂ) :
    Complex.I • resolventBlock n v - (diracEigen n : ℂ) * resolventBlock n v = v := by
  have hne : Complex.I - (diracEigen n : ℂ) ≠ 0 := by
    intro h
    have h1 := norm_sub_eigen_ge_one n
    rw [h, norm_zero] at h1
    linarith
  unfold resolventBlock
  simp only [ContinuousLinearMap.smul_apply, ContinuousLinearMap.id_apply, smul_eq_mul]
  field_simp

private lemma resolventBlock_dirac_apply (n : ℤ) (v : ℂ) :
    (diracEigen n : ℂ) * resolventBlock n v = Complex.I • resolventBlock n v - v := by
  have h := sub_eq_iff_eq_add'.mp (resolventBlock_left_inverse n v)
  rw [eq_sub_iff_add_eq]
  exact h.symm

private lemma resolventDiag_mem_diracDomain (a : L2) : resolventDiag a ∈ diracDomain := by
  rw [mem_diracDomain_iff]
  have hfun : (fun n => (diracEigen n : ℂ) * (resolventDiag a) n) =
      fun n => (Complex.I • resolventDiag a - a) n := by
    funext n
    rw [resolventDiag, lpDiag.diagL_apply, resolventBlock_dirac_apply]
    rfl
  rw [hfun]
  exact lp.memℓp _

private lemma resolvent_op_resolventDiag (a : L2) :
    (((Complex.I • LinearMap.id (R := ℂ) (M := L2)) +ᵥ (-diracDirac) : L2 →ₗ.[ℂ] L2)
      ⟨resolventDiag a, resolventDiag_mem_diracDomain a⟩) = a := by
  refine lp.ext (funext fun n => ?_)
  rw [vadd_apply, LinearMap.smul_apply, LinearMap.id_apply, neg_apply]
  change (Complex.I • resolventDiag a -
      diracDirac ⟨resolventDiag a, resolventDiag_mem_diracDomain a⟩) n = a n
  rw [lp.coeFn_sub, Pi.sub_apply, lp.coeFn_smul, Pi.smul_apply, diracDirac_apply]
  simpa only [resolventDiag, lpDiag.diagL_apply] using resolventBlock_left_inverse n (a n)

private lemma resolvent_eq_resolventDiag :
    diracDirac.resolvent Complex.I = (resolventDiag : L2 →ₗ[ℂ] L2) := by
  rw [LinearPMap.resolvent_apply_eq (f := diracDirac) mem_resolventSet_I]
  apply LinearMap.ext
  intro a
  have h := LinearPMap.apply_inverseAsLinearMap_apply_cancel
      (f := ((Complex.I • LinearMap.id (R := ℂ) (M := L2)) +ᵥ (-diracDirac) : L2 →ₗ.[ℂ] L2))
      mem_resolventSet_I
      (⟨resolventDiag a, resolventDiag_mem_diracDomain a⟩ :
        (((Complex.I • LinearMap.id (R := ℂ) (M := L2)) +ᵥ (-diracDirac) : L2 →ₗ.[ℂ] L2).domain))
  rw [resolvent_op_resolventDiag] at h
  exact h

/-- The resolvent of the circle Dirac operator at `i` is compact. -/
theorem isCompactOperator_resolvent_I :
    IsCompactOperator (diracDirac.resolvent Complex.I) := by
  rw [resolvent_eq_resolventDiag]
  exact isCompactOperator_resolventDiag

/-! ### The Fourier shift representation -/

/-- Reindexing an `ℓ²(ℤ)` vector by right addition preserves square-summability. -/
theorem shift_memℓp (g : ℤ) (ψ : L2) : Memℓp (fun n : ℤ => ψ (n + g)) 2 := by
  rw [memℓp_gen_iff (by norm_num : 0 < (2 : ℝ≥0∞).toReal)]
  have hψ : Summable (fun n : ℤ => ‖ψ n‖ ^ (2 : ℝ≥0∞).toReal) :=
    (lp.memℓp ψ).summable (by norm_num : 0 < (2 : ℝ≥0∞).toReal)
  simpa [Function.comp_def] using ((Equiv.addRight g).summable_iff).mpr hψ

/-- The right-translation shift `(shiftFun g ψ)ₙ = ψₙ₊g` on Fourier coefficients. -/
noncomputable def shiftFun (g : ℤ) (ψ : L2) : L2 :=
  ⟨fun n : ℤ => ψ (n + g), shift_memℓp g ψ⟩

@[simp] theorem shiftFun_apply (g : ℤ) (ψ : L2) (n : ℤ) : (shiftFun g ψ) n = ψ (n + g) := rfl

/-- The shift is norm-preserving. -/
theorem norm_shiftFun (g : ℤ) (ψ : L2) : ‖shiftFun g ψ‖ = ‖ψ‖ := by
  have hp : 0 < (2 : ℝ≥0∞).toReal := by norm_num
  have hpow : ‖shiftFun g ψ‖ ^ (2 : ℝ≥0∞).toReal = ‖ψ‖ ^ (2 : ℝ≥0∞).toReal := by
    rw [lp.norm_rpow_eq_tsum hp, lp.norm_rpow_eq_tsum hp]
    exact (Equiv.addRight g).tsum_eq (fun q : ℤ => ‖ψ q‖ ^ (2 : ℝ≥0∞).toReal)
  norm_num at hpow
  exact hpow

/-- The unitary shift of `L2 = ℓ²(ℤ)` by an integer. -/
noncomputable def shiftEquiv (g : ℤ) : L2 ≃ₗᵢ[ℂ] L2 where
  toFun := shiftFun g
  invFun := shiftFun (-g)
  left_inv := by
    intro ψ
    refine lp.ext (funext fun n => ?_)
    simp [shiftFun_apply, add_assoc]
  right_inv := by
    intro ψ
    refine lp.ext (funext fun n => ?_)
    simp [shiftFun_apply, add_assoc]
  map_add' := by
    intro ψ φ
    refine lp.ext (funext fun n => ?_)
    simp only [shiftFun_apply, lp.coeFn_add, Pi.add_apply]
  map_smul' := by
    intro c ψ
    refine lp.ext (funext fun n => ?_)
    simp only [shiftFun_apply, lp.coeFn_smul, Pi.smul_apply, RingHom.id_apply]
  norm_map' := norm_shiftFun g

/-- The Fourier shift unitary `(W g ψ)ₙ = ψₙ₊g`. This single generator (at `g = 1`) represents
the coordinate function `e^{iθ}` of the circle algebra on the Fourier side. -/
noncomputable def W (g : ℤ) : L2 →L[ℂ] L2 := (shiftEquiv g : L2 →L[ℂ] L2)

@[simp] theorem W_apply (g : ℤ) (ψ : L2) (n : ℤ) : (W g ψ) n = ψ (n + g) := rfl

theorem W_zero : W 0 = 1 := by
  refine ContinuousLinearMap.ext fun ψ => ?_
  refine lp.ext (funext fun n => ?_)
  simp [W_apply]

theorem W_mul (g₁ g₂ : ℤ) : W g₁ * W g₂ = W (g₁ + g₂) := by
  refine ContinuousLinearMap.ext fun ψ => ?_
  refine lp.ext (funext fun n => ?_)
  simp [W_apply, ContinuousLinearMap.mul_apply, add_assoc]

theorem W_star (g : ℤ) : star (W g) = W (-g) := by
  have hsymm : (shiftEquiv g).symm = shiftEquiv (-g) := by
    refine LinearIsometryEquiv.ext fun ψ => ?_
    rfl
  unfold W
  rw [LinearIsometryEquiv.star_eq_symm, hsymm]

private lemma diracEigen_add (n g : ℤ) :
    (diracEigen (n + g) : ℂ) = (diracEigen n : ℂ) + (diracEigen g : ℂ) := by
  unfold diracEigen; push_cast; ring

private theorem W_mem_diracDomain (g : ℤ) {x : L2} (hx : x ∈ diracDomain) :
    W g x ∈ diracDomain := by
  rw [mem_diracDomain_iff]
  let xd : diracDomain := ⟨x, hx⟩
  have hfun : (fun n : ℤ => (diracEigen n : ℂ) * (W g x) n) =
      fun n : ℤ => (W g (diracDirac xd) - (diracEigen g : ℂ) • W g x) n := by
    funext n
    rw [W_apply, lp.coeFn_sub, Pi.sub_apply, W_apply, diracDirac_apply, lp.coeFn_smul,
      Pi.smul_apply, W_apply, smul_eq_mul]
    rw [diracEigen_add n g]
    ring
  rw [hfun]
  exact lp.memℓp _

private theorem W_commutator (g : ℤ) (x : diracDomain) :
    W g (diracDirac x) - diracDirac ⟨W g (x : L2), W_mem_diracDomain g x.2⟩ =
      (diracEigen g : ℂ) • W g (x : L2) := by
  refine lp.ext (funext fun n => ?_)
  rw [lp.coeFn_sub, Pi.sub_apply, W_apply, diracDirac_apply, diracDirac_apply, lp.coeFn_smul,
    Pi.smul_apply, W_apply, smul_eq_mul]
  rw [diracEigen_add n g]
  ring

private def MapsDom (T : L2 →L[ℂ] L2) : Prop :=
  ∀ x : L2, x ∈ diracDomain → T x ∈ diracDomain

private def CommBdd (T : L2 →L[ℂ] L2) (hT : MapsDom T) : Prop :=
  ∃ B : L2 →L[ℂ] L2, ∀ x : diracDomain,
    T (diracDirac x) - diracDirac ⟨T (x : L2), hT (x : L2) x.2⟩ = B (x : L2)

private def Smooth (T : L2 →L[ℂ] L2) : Prop :=
  ∃ hT : MapsDom T, CommBdd T hT

private def Smooth' (T : L2 →L[ℂ] L2) : Prop :=
  Smooth T ∧ Smooth (star T)

private theorem smooth_algebraMap (c : ℂ) :
    Smooth (algebraMap ℂ (L2 →L[ℂ] L2) c) := by
  let T : L2 →L[ℂ] L2 := algebraMap ℂ (L2 →L[ℂ] L2) c
  have hT : MapsDom T := by
    intro x hx
    simpa [T, ContinuousLinearMap.algebraMap_apply] using diracDomain.smul_mem c hx
  refine ⟨hT, 0, fun x => ?_⟩
  rw [ContinuousLinearMap.zero_apply]
  change c • diracDirac x - diracDirac (c • x) = 0
  rw [show diracDirac (c • x) = c • diracDirac x from diracDirac.map_smul c x, sub_self]

private theorem smooth'_algebraMap (c : ℂ) :
    Smooth' (algebraMap ℂ (L2 →L[ℂ] L2) c) := by
  refine ⟨smooth_algebraMap c, ?_⟩
  simpa [← algebraMap_star_comm (A := L2 →L[ℂ] L2) c] using smooth_algebraMap (star c)

private theorem smooth_add {S T : L2 →L[ℂ] L2} (hS : Smooth S) (hT : Smooth T) :
    Smooth (S + T) := by
  rcases hS with ⟨hSdom, BS, hBS⟩
  rcases hT with ⟨hTdom, BT, hBT⟩
  have hdom : MapsDom (S + T) := by
    intro x hx
    simpa [ContinuousLinearMap.add_apply] using diracDomain.add_mem (hSdom x hx) (hTdom x hx)
  refine ⟨hdom, BS + BT, fun x => ?_⟩
  have hSx : S (x : L2) ∈ diracDomain := hSdom (x : L2) x.2
  have hTx : T (x : L2) ∈ diracDomain := hTdom (x : L2) x.2
  have hDadd :
      diracDirac ⟨(S + T) (x : L2), hdom (x : L2) x.2⟩ =
        diracDirac (⟨S (x : L2), hSx⟩ + ⟨T (x : L2), hTx⟩ : diracDomain) := by
    congr 1
  rw [ContinuousLinearMap.add_apply, hDadd]
  rw [show diracDirac (⟨S (x : L2), hSx⟩ + ⟨T (x : L2), hTx⟩ : diracDomain) =
      diracDirac ⟨S (x : L2), hSx⟩ + diracDirac ⟨T (x : L2), hTx⟩ from
        diracDirac.map_add _ _]
  rw [ContinuousLinearMap.add_apply, ← hBS x, ← hBT x]
  abel

private theorem smooth'_add {S T : L2 →L[ℂ] L2} (hS : Smooth' S) (hT : Smooth' T) :
    Smooth' (S + T) := by
  refine ⟨smooth_add hS.1 hT.1, ?_⟩
  simpa [star_add] using smooth_add hS.2 hT.2

private theorem smooth_mul {S T : L2 →L[ℂ] L2} (hS : Smooth S) (hT : Smooth T) :
    Smooth (S * T) := by
  rcases hS with ⟨hSdom, BS, hBS⟩
  rcases hT with ⟨hTdom, BT, hBT⟩
  have hdom : MapsDom (S * T) := by
    intro x hx
    simpa [ContinuousLinearMap.mul_apply] using hSdom (T x) (hTdom x hx)
  refine ⟨hdom, S.comp BT + BS.comp T, fun x => ?_⟩
  let y : diracDomain := ⟨T (x : L2), hTdom (x : L2) x.2⟩
  have hBTy : T (diracDirac x) - diracDirac y = BT (x : L2) := by
    simpa [y] using hBT x
  have hD :
      diracDirac ⟨(S * T) (x : L2), hdom (x : L2) x.2⟩ =
        diracDirac ⟨S (y : L2), hSdom (y : L2) y.2⟩ := by
    congr 1
  rw [ContinuousLinearMap.mul_apply, hD]
  rw [ContinuousLinearMap.add_apply, ContinuousLinearMap.comp_apply,
    ContinuousLinearMap.comp_apply]
  calc
    S (T (diracDirac x)) - diracDirac ⟨S (y : L2), hSdom (y : L2) y.2⟩
        = S (T (diracDirac x)) - S (diracDirac y) +
            (S (diracDirac y) - diracDirac ⟨S (y : L2), hSdom (y : L2) y.2⟩) := by
          abel
    _ = S (T (diracDirac x) - diracDirac y) +
            (S (diracDirac y) - diracDirac ⟨S (y : L2), hSdom (y : L2) y.2⟩) := by
          rw [_root_.map_sub]
    _ = S (BT (x : L2)) + BS (y : L2) := by rw [hBTy, hBS y]
    _ = S (BT (x : L2)) + BS (T (x : L2)) := by rfl

private theorem smooth'_mul {S T : L2 →L[ℂ] L2} (hS : Smooth' S) (hT : Smooth' T) :
    Smooth' (S * T) := by
  refine ⟨smooth_mul hS.1 hT.1, ?_⟩
  simpa [star_mul] using smooth_mul hT.2 hS.2

private theorem smooth'_star {T : L2 →L[ℂ] L2} (hT : Smooth' T) : Smooth' (star T) := by
  refine ⟨hT.2, ?_⟩
  simpa using hT.1

private theorem smooth_W (g : ℤ) : Smooth (W g) := by
  have hdom : MapsDom (W g) := fun x hx => W_mem_diracDomain g hx
  exact ⟨hdom, (diracEigen g : ℂ) • W g, fun x => W_commutator g x⟩

private theorem smooth'_W (g : ℤ) : Smooth' (W g) := by
  refine ⟨smooth_W g, ?_⟩
  rw [W_star]
  exact smooth_W (-g)

/-- The star-subalgebra of bounded operators generated by the Fourier shift unitary `W 1`,
the Fourier image of the trigonometric polynomials `ℂ[ℤ]` on the circle. -/
noncomputable def algebra : StarSubalgebra ℂ (L2 →L[ℂ] L2) :=
  StarAlgebra.adjoin ℂ ({W 1} : Set (L2 →L[ℂ] L2))

/-- The faithful representation of the generated circle algebra by inclusion into bounded
operators on `L2`. -/
noncomputable def rep : algebra →⋆ₐ[ℂ] (L2 →L[ℂ] L2) :=
  algebra.subtype

private theorem smooth'_algebra (a : algebra) : Smooth' (a : L2 →L[ℂ] L2) := by
  exact StarAlgebra.adjoin_induction_subtype
    (s := ({W 1} : Set (L2 →L[ℂ] L2)))
    (p := fun a : algebra => Smooth' (a : L2 →L[ℂ] L2)) a
    (fun x hx => by
      simp only [Set.mem_singleton_iff] at hx
      rcases hx with rfl
      exact smooth'_W 1)
    (fun c => by simpa using smooth'_algebraMap c)
    (fun _ _ hx hy => by simpa using smooth'_add hx hy)
    (fun _ _ hx hy => by simpa using smooth'_mul hx hy)
    (fun _ hx => by simpa using smooth'_star hx)

private theorem rep_maps_diracDomain (a : algebra) (x : diracDomain) :
    rep a (x : L2) ∈ diracDomain := by
  rcases (smooth'_algebra a).1 with ⟨hdom, _⟩
  exact hdom (x : L2) x.2

private theorem odd_comm_bound (a : algebra) :
    (iSup fun (x : Metric.closedBall (0 : diracDirac.domain) 1) ↦
      ‖(rep a) (diracDirac (x : diracDirac.domain)) -
        (diracDirac ⟨(rep a) (x : diracDirac.domain),
          rep_maps_diracDomain a (x : diracDirac.domain)⟩)‖ₑ) < ∞ := by
  rcases (smooth'_algebra a).1 with ⟨hdom, B, hB⟩
  refine lt_of_le_of_lt (iSup_le fun x => ?_) (enorm_lt_top (x := B))
  let y : diracDomain := (x : diracDirac.domain)
  have hnorm : ‖(y : L2)‖ ≤ 1 := by
    have hx' : dist (x : diracDirac.domain) 0 ≤ 1 := x.2
    simpa [dist_eq_norm, y] using hx'
  have hnorme : ‖(y : L2)‖ₑ ≤ (1 : ℝ≥0∞) := by
    rw [← ofReal_norm, ← ENNReal.ofReal_one]
    exact ENNReal.ofReal_le_ofReal hnorm
  have hD :
      diracDirac ⟨(rep a) (y : L2), rep_maps_diracDomain a y⟩ =
        diracDirac ⟨(rep a) (y : L2), hdom (y : L2) y.2⟩ := by
    congr 1
  calc
    ‖(rep a) (diracDirac y) -
        diracDirac ⟨(rep a) (y : L2), rep_maps_diracDomain a y⟩‖ₑ
        = ‖B (y : L2)‖ₑ := by
          rw [hD]
          simpa [rep] using congrArg (fun z : L2 => ‖z‖ₑ) (hB y)
    _ ≤ ‖B‖ₑ := by
      calc
        ‖B (y : L2)‖ₑ ≤ ‖B‖ₑ * ‖(y : L2)‖ₑ := B.le_opNorm_enorm _
        _ ≤ ‖B‖ₑ * 1 := by
          simpa [mul_comm] using mul_le_mul_left (a := ‖B‖ₑ) hnorme
        _ = ‖B‖ₑ := by rw [mul_one]

/-- The generated circle representation, together with the circle Dirac operator, is an odd
spectral triple. -/
theorem isOddSpectralTriple : IsOddSpectralTriple algebra diracDirac rep where
  self_adjoint := diracDirac_isSelfAdjoint
  dom_comp := rep_maps_diracDomain
  comm := odd_comm_bound

/-- The circle spectral triple has compact resolvent at `i`, hence is finitely summable in the
basic compact-resolvent sense used in this development. -/
theorem isFinitelySummableSpectralTriple :
    IsFinitelySummableSpectralTriple algebra diracDirac rep :=
  isOddSpectralTriple.toIsFinitelySummableSpectralTriple (by simp) isCompactOperator_resolvent_I

end SpectralTriples.Circle
