/-
Copyright (c) 2026 Jon Bannon. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Bannon, Michael R. Douglas
-/

module

public import SpectralTriples.FinitelySummable
public import SpectralTriples.Index
public import SpectralTriples.DiagonalOperator
public import Mathlib.Algebra.Star.Subalgebra
public import Mathlib.Analysis.CStarAlgebra.Matrix
public import Mathlib.Analysis.InnerProductSpace.l2Space
public import Mathlib.Analysis.Matrix.Hermitian
public import Mathlib.Order.Interval.Finset.Box
public import Mathlib.Order.Northcott

/-! # The Dirac spectral triple of the 2-torus `T²`

The simplest **even** (`Z₂`-graded) concrete spectral triple, built on the Fourier side. The
flat torus `T² = ℝ²/ℤ²` has trivial spin structure; the spinor bundle is rank 2, and on the
Fourier mode `(m, n) ∈ ℤ²` the Dirac operator acts on the spinor fibre `ℂ²` by the
self-adjoint block
`D₍ₘ,ₙ₎ = 2π (σ₁ m + σ₂ n) = 2π · !![0, m - i·n; m + i·n, 0]`,
with eigenvalues `± 2π √(m² + n²)`. The chirality is `γ = σ₃ = diag(1, -1)`.

* `H = ℓ²(ℤ²; ℂ²)` (`lp (fun _ : ℤ × ℤ => EuclideanSpace ℂ (Fin 2)) 2`), the Hilbert space.
* `D` is block-diagonal, self-adjoint, with `(D + i)⁻¹` compact (`|2π√(m²+n²)| → ∞`).
* `γ` is a self-adjoint unitary involution, commuting with the (scalar) representation and
  anticommuting with `D` (since each block is off-diagonal and `γ` is diagonal).

This reuses the `S¹` strategy (a diagonal operator on `lp 2`, self-adjointness by testing
against `lp.single`, compact resolvent by finite-rank truncation), upgraded from scalar
eigenvalues to **self-adjoint 2×2 blocks** on the spinor fibre.

## Construction status and plan

All steps are complete: the Hilbert space, the block-diagonal Dirac operator, its
**self-adjointness** (hence `i ∈ ρ(D)`), **compact resolvent**, the **grading** `γ = σ₃`, the
**representation** of the trigonometric-polynomial algebra `ℂ[ℤ²]` by Fourier shifts, and the
**assembly** as an even, finitely-summable spectral triple.

1. **Hilbert space** `H = ℓ²(ℤ²; ℂ²)` — done.
2. **Dirac block** `diracBlock (m,n) : ℂ² →L[ℂ] ℂ²`, the self-adjoint matrix above; then the
   block-diagonal `D : H →ₗ.[ℂ] H`, `(D a)₍ₘ,ₙ₎ = diracBlock (m,n) (a ₍ₘ,ₙ₎)`, on the `H¹`
   domain `diracDomain` below — done.
3. **Self-adjointness** `IsSelfAdjoint D` — done: the block version of the `S¹` argument —
   symmetry from `inner_eq_tsum` + self-adjointness of each block; the adjoint-domain inclusion
   by testing against `lp.single (m,n) v` for single-mode spinors. `i ∈ ρ(D)` follows.
4. **Compact resolvent** `IsCompactOperator (D.resolvent i)` — done: the resolvent is the
   block-diagonal operator with blocks `(i·1 − D₍ₚ₎)⁻¹ = (1+|D₍ₚ₎|²)⁻¹(−i·1 − D₍ₚ₎)`, whose
   norms `→ 0` (since `|D₍ₚ₎| = 2π√(m²+n²) → ∞`); compactness then comes from the finite-rank
   truncation criterion `lpDiag.isCompactOperator_diagL`.
5. **Grading** `γ : H →L[ℂ] H` (fibrewise `σ₃`) — done: self-adjoint (`isSelfAdjoint_grading`),
   `γ² = 1` (`grading_mul_self`), domain-preserving (`grading_mem_diracDomain`), and
   anticommuting `D γ = -γ D` (`grading_anticomm`), since each `σ₃` anticommutes with the
   off-diagonal Dirac block.
6. **Representation** `rep : algebra →⋆ₐ[ℂ] 𝓑(H)` — done: `algebra` is the star-subalgebra
   generated by the two coordinate shift unitaries `W (1,0)`, `W (0,1)` (the Fourier image of
   the trigonometric polynomials `ℂ[ℤ²]`), and `rep` is the inclusion. Each shift preserves the
   `H¹` domain and has bounded commutator `[D, W g] = -(σ·g) W g`; these properties propagate to
   all of `algebra` by `StarAlgebra.adjoin_induction`.
7. **Assemble** — done: `isOddSpectralTriple`, `isEvenSpectralTriple` (the grading commutes with
   the scalar-on-fibres shifts), and via `toIsFinitelySummableSpectralTriple` the finitely
   summable triple `isFinitelySummableSpectralTriple` at `i`.
-/

@[expose] public section

open LinearPMap
open Filter
open scoped Topology Matrix.Norms.L2Operator ENNReal

namespace SpectralTriples.Torus

/-- The spinor fibre `ℂ²` (with its Hilbert-space structure). -/
abbrev Spinor : Type := EuclideanSpace ℂ (Fin 2)

/-- The Hilbert space `ℓ²(ℤ²; ℂ²)` of the `T²` Dirac triple: square-summable spinor-valued
sequences over the Fourier lattice `ℤ²`. -/
abbrev H : Type := lp (fun _ : ℤ × ℤ => Spinor) 2

noncomputable instance : NormedAddCommGroup H := inferInstance
noncomputable instance : InnerProductSpace ℂ H := inferInstance
instance : CompleteSpace H := inferInstance

/-- The magnitude of the Dirac eigenvalues on the Fourier mode `(m, n)`: the block
`2π(σ₁ m + σ₂ n)` has eigenvalues `± 2π √(m² + n²)`, all of magnitude `diracMagnitude (m, n)`.
This tends to `∞` as `(m, n) → ∞`, which is what makes the resolvent compact. -/
noncomputable def diracMagnitude : ℤ × ℤ → ℝ :=
  fun p => 2 * Real.pi * Real.sqrt ((p.1 : ℝ) ^ 2 + (p.2 : ℝ) ^ 2)

/-- The Dirac block on the Fourier mode `(m, n)`: the self-adjoint matrix
`2π · !![0, m - i·n; m + i·n, 0]`, as a linear endomorphism of the spinor fibre `ℂ²`. -/
noncomputable def diracBlock (p : ℤ × ℤ) : Spinor →ₗ[ℂ] Spinor :=
  Matrix.toEuclideanLin <| (2 * Real.pi : ℂ) •
    !![0, (p.1 : ℂ) - (p.2 : ℂ) * Complex.I;
       (p.1 : ℂ) + (p.2 : ℂ) * Complex.I, 0]

/-- Each Dirac block is self-adjoint on the spinor fibre: the matrix
`2π·!![0, m-in; m+in, 0]` is Hermitian. -/
theorem diracBlock_isSymmetric (p : ℤ × ℤ) : (diracBlock p).IsSymmetric := by
  rw [diracBlock, Matrix.isSymmetric_toEuclideanLin_iff]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.conjTranspose_apply, Matrix.smul_apply, Complex.conj_ofReal, sub_eq_add_neg]

/-- The maximal domain of the torus Dirac operator: the `H¹` Sobolev space, those `a` for which
`p ↦ D₍ₚ₎ (aₚ)` is again square-summable (equivalently `Σ (m²+n²) ‖aₚ‖² < ∞`). An instance of
the generic symmetric-block-diagonal machinery of `lpDiag`. -/
noncomputable def diracDomain : Submodule ℂ H := lpDiag.diracDomain diracBlock

theorem mem_diracDomain_iff (a : H) :
    a ∈ diracDomain ↔ Memℓp (fun p => diracBlock p (a p)) 2 :=
  lpDiag.mem_diracDomain_iff diracBlock a

/-- The torus Dirac operator as an unbounded `LinearPMap`: block-diagonal on the Fourier
lattice, `(D a)₍ₘ,ₙ₎ = D₍ₘ,ₙ₎ (a₍ₘ,ₙ₎)`, with domain the `H¹` Sobolev space `diracDomain`. -/
noncomputable def diracDirac : H →ₗ.[ℂ] H := lpDiag.diracDirac diracBlock

@[simp] theorem diracDirac_apply (a : diracDomain) (p : ℤ × ℤ) :
    (diracDirac a) p = diracBlock p ((a : H) p) :=
  lpDiag.diracDirac_apply diracBlock a p

/-- **The torus Dirac operator is self-adjoint.** An instance of the generic
`lpDiag.diracDirac_isSelfAdjoint` for symmetric block families. -/
theorem diracDirac_isSelfAdjoint : IsSelfAdjoint diracDirac :=
  lpDiag.diracDirac_isSelfAdjoint diracBlock diracBlock_isSymmetric

/-- `i` lies in the resolvent set of the torus Dirac operator: it is self-adjoint and
`Im i = 1 ≠ 0`, so the basic criterion applies. -/
theorem mem_resolventSet_I : Complex.I ∈ diracDirac.resolventSet :=
  diracDirac_isSelfAdjoint.mem_resolventSet (by simp)

private noncomputable def diracMatrix (p : ℤ × ℤ) : Matrix (Fin 2) (Fin 2) ℂ :=
  (2 * Real.pi : ℂ) •
    !![0, (p.1 : ℂ) - (p.2 : ℂ) * Complex.I;
       (p.1 : ℂ) + (p.2 : ℂ) * Complex.I, 0]

private noncomputable def diracSq (p : ℤ × ℤ) : ℝ :=
  (2 * Real.pi) ^ 2 * ((p.1 : ℝ) ^ 2 + (p.2 : ℝ) ^ 2)

private lemma diracMagnitude_nonneg (p : ℤ × ℤ) : 0 ≤ diracMagnitude p := by
  unfold diracMagnitude
  positivity

private lemma diracMagnitude_sq (p : ℤ × ℤ) :
    diracMagnitude p ^ 2 = diracSq p := by
  have hnonneg : 0 ≤ (p.1 : ℝ) ^ 2 + (p.2 : ℝ) ^ 2 := by positivity
  unfold diracMagnitude diracSq
  rw [mul_pow, Real.sq_sqrt hnonneg]

private lemma diracSq_nonneg (p : ℤ × ℤ) : 0 ≤ diracSq p := by
  rw [← diracMagnitude_sq]
  positivity

private lemma diracMatrix_conjTranspose (p : ℤ × ℤ) :
    (diracMatrix p).conjTranspose = diracMatrix p := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [diracMatrix, Matrix.conjTranspose_apply, Matrix.smul_apply, Complex.conj_ofReal,
      sub_eq_add_neg]

private lemma diracMatrix_sq (p : ℤ × ℤ) :
    diracMatrix p * diracMatrix p =
      ((diracSq p : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [diracMatrix, diracSq, Matrix.mul_apply, Fin.sum_univ_two, Matrix.smul_apply,
      sub_eq_add_neg]
    <;> ring_nf
    <;> rw [Complex.I_sq]
    <;> ring_nf

private lemma norm_diracMatrix (p : ℤ × ℤ) : ‖diracMatrix p‖ = diracMagnitude p := by
  have h := Matrix.l2_opNorm_conjTranspose_mul_self (diracMatrix p)
  rw [diracMatrix_conjTranspose, diracMatrix_sq] at h
  have hleft :
      ‖((diracSq p : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)‖ =
        diracMagnitude p ^ 2 := by
    rw [show (((diracSq p : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)) =
        Matrix.diagonal (fun _ : Fin 2 => ((diracSq p : ℝ) : ℂ)) by
      ext i j
      by_cases hij : i = j <;> simp [hij, Matrix.smul_apply]]
    rw [Matrix.l2_opNorm_diagonal]
    simp [Pi.norm_def, Finset.sup_const Finset.univ_nonempty, Real.nnnorm_of_nonneg,
      diracSq_nonneg, diracMagnitude_sq]
  have hsq : ‖diracMatrix p‖ ^ 2 = diracMagnitude p ^ 2 := by
    rw [pow_two]
    rw [← h, hleft]
  exact sq_eq_sq₀ (norm_nonneg _) (diracMagnitude_nonneg p) |>.mp hsq

private lemma diracBlock_sq_apply (p : ℤ × ℤ) (v : Spinor) :
    diracBlock p (diracBlock p v) = ((diracMagnitude p ^ 2 : ℝ) : ℂ) • v := by
  apply WithLp.ofLp_injective (p := 2)
  change WithLp.ofLp ((Matrix.toLpLin 2 2 (diracMatrix p))
      ((Matrix.toLpLin 2 2 (diracMatrix p)) v)) =
    WithLp.ofLp (((diracMagnitude p ^ 2 : ℝ) : ℂ) • v)
  rw [Matrix.ofLp_toLpLin, Matrix.ofLp_toLpLin, Matrix.toLin'_apply, Matrix.toLin'_apply,
    Matrix.mulVec_mulVec, diracMatrix_sq, ← diracMagnitude_sq]
  simp [Matrix.smul_mulVec]

private noncomputable def diracBlockL (p : ℤ × ℤ) : Spinor →L[ℂ] Spinor :=
  Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℂ) (diracMatrix p)

@[simp] private lemma coe_diracBlockL (p : ℤ × ℤ) :
    (diracBlockL p : Spinor →ₗ[ℂ] Spinor) = diracBlock p := rfl

@[simp] private lemma diracBlockL_apply (p : ℤ × ℤ) (v : Spinor) :
    diracBlockL p v = diracBlock p v := by
  change (diracBlockL p : Spinor →ₗ[ℂ] Spinor) v = diracBlock p v
  rw [coe_diracBlockL]

private lemma norm_diracBlockL (p : ℤ × ℤ) : ‖diracBlockL p‖ = diracMagnitude p := by
  change ‖Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℂ) (diracMatrix p)‖ = diracMagnitude p
  rw [Matrix.l2_opNorm_toEuclideanCLM, norm_diracMatrix]

private noncomputable def resolventBlock (p : ℤ × ℤ) : Spinor →L[ℂ] Spinor :=
  (((1 / (1 + diracMagnitude p ^ 2) : ℝ) : ℂ)) •
    (-(Complex.I) • ContinuousLinearMap.id ℂ Spinor - diracBlockL p)

private lemma norm_resolventBlock_le_bound (p : ℤ × ℤ) :
    ‖resolventBlock p‖ ≤ (1 + diracMagnitude p) / (1 + diracMagnitude p ^ 2) := by
  let s : ℂ := ((1 / (1 + diracMagnitude p ^ 2) : ℝ) : ℂ)
  let T : Spinor →L[ℂ] Spinor :=
    -(Complex.I) • ContinuousLinearMap.id ℂ Spinor - diracBlockL p
  have hs : ‖s‖ = 1 / (1 + diracMagnitude p ^ 2) := by
    dsimp [s]
    rw [show ‖((1 / (1 + diracMagnitude p ^ 2) : ℝ) : ℂ)‖ =
        |(1 / (1 + diracMagnitude p ^ 2) : ℝ)| from RCLike.norm_ofReal (K := ℂ) _]
    rw [abs_of_nonneg]
    positivity
  have hIid : ‖-(Complex.I) • ContinuousLinearMap.id ℂ Spinor‖ = 1 := by
    rw [norm_smul, ContinuousLinearMap.norm_id]
    simp
  have hT : ‖T‖ ≤ 1 + diracMagnitude p := by
    dsimp [T]
    calc
      ‖-(Complex.I) • ContinuousLinearMap.id ℂ Spinor - diracBlockL p‖
          ≤ ‖-(Complex.I) • ContinuousLinearMap.id ℂ Spinor‖ + ‖diracBlockL p‖ := norm_sub_le _ _
      _ = 1 + diracMagnitude p := by
        rw [hIid, norm_diracBlockL]
  calc
    ‖resolventBlock p‖ = ‖s • T‖ := rfl
    _ = ‖s‖ * ‖T‖ := norm_smul _ _
    _ ≤ (1 / (1 + diracMagnitude p ^ 2)) * (1 + diracMagnitude p) := by
      rw [hs]
      gcongr
    _ = (1 + diracMagnitude p) / (1 + diracMagnitude p ^ 2) := by ring

private lemma resolventBlock_left_inverse (p : ℤ × ℤ) (v : Spinor) :
    Complex.I • resolventBlock p v - diracBlock p (resolventBlock p v) = v := by
  let s : ℂ := ((1 / (1 + diracMagnitude p ^ 2) : ℝ) : ℂ)
  let d : ℂ := ((diracMagnitude p ^ 2 : ℝ) : ℂ)
  have hden : (1 + diracMagnitude p ^ 2 : ℝ) ≠ 0 := by positivity
  have hs : s * (1 + d) = 1 := by
    have hreal : (1 / (1 + diracMagnitude p ^ 2)) *
        (1 + diracMagnitude p ^ 2) = (1 : ℝ) := by
      field_simp [hden]
    dsimp [s, d]
    exact_mod_cast hreal
  have hscalar : -(Complex.I ^ 2 * s) + s * d = 1 := by
    rw [Complex.I_sq]
    simpa [mul_add] using hs
  unfold resolventBlock
  simp only [ContinuousLinearMap.smul_apply, ContinuousLinearMap.sub_apply,
    ContinuousLinearMap.id_apply, diracBlockL_apply]
  rw [_root_.map_smul, _root_.map_sub, _root_.map_smul, diracBlock_sq_apply]
  change Complex.I • s • (-Complex.I • v - diracBlock p v) -
      s • (-Complex.I • diracBlock p v - d • v) = v
  calc
    Complex.I • s • (-Complex.I • v - diracBlock p v) -
        s • (-Complex.I • diracBlock p v - d • v)
        = (-(Complex.I ^ 2 * s) + s * d) • v := by module
    _ = v := by rw [hscalar, one_smul]

private lemma resolventBlock_dirac_apply (p : ℤ × ℤ) (v : Spinor) :
    diracBlock p (resolventBlock p v) = Complex.I • resolventBlock p v - v := by
  have h := sub_eq_iff_eq_add'.mp (resolventBlock_left_inverse p v)
  rw [eq_sub_iff_add_eq]
  exact h.symm

private def radius (p : ℤ × ℤ) : ℕ := max p.1.natAbs p.2.natAbs

private lemma radius_northcott : Northcott radius where
  finite_le n := by
    classical
    let s : Finset (ℤ × ℤ) := (Finset.range (n + 1)).biUnion fun k => Finset.box k
    refine s.finite_toSet.subset ?_
    intro p hp
    rw [Finset.mem_coe, Finset.mem_biUnion]
    refine ⟨radius p, ?_, ?_⟩
    · rw [Finset.mem_range]
      exact Nat.lt_succ_of_le hp
    · exact Int.mem_box.mpr rfl

private lemma radius_tendsto_atTop : Tendsto radius cofinite atTop := by
  rw [← northcott_iff_tendsto]
  exact radius_northcott

private lemma radius_le_sqrt (p : ℤ × ℤ) :
    (radius p : ℝ) ≤ Real.sqrt ((p.1 : ℝ) ^ 2 + (p.2 : ℝ) ^ 2) := by
  have hsum : 0 ≤ (p.1 : ℝ) ^ 2 + (p.2 : ℝ) ^ 2 := by positivity
  have h1 : ((p.1.natAbs : ℕ) : ℝ) ^ 2 ≤ (p.1 : ℝ) ^ 2 + (p.2 : ℝ) ^ 2 := by
    have habs : ((p.1.natAbs : ℕ) : ℝ) = |(p.1 : ℝ)| := by
      simpa only [Int.cast_abs] using (Nat.cast_natAbs (α := ℝ) p.1)
    rw [habs, sq_abs]
    nlinarith [sq_nonneg (p.2 : ℝ)]
  have h2 : ((p.2.natAbs : ℕ) : ℝ) ^ 2 ≤ (p.1 : ℝ) ^ 2 + (p.2 : ℝ) ^ 2 := by
    have habs : ((p.2.natAbs : ℕ) : ℝ) = |(p.2 : ℝ)| := by
      simpa only [Int.cast_abs] using (Nat.cast_natAbs (α := ℝ) p.2)
    rw [habs, sq_abs]
    nlinarith [sq_nonneg (p.1 : ℝ)]
  have hsq : (radius p : ℝ) ^ 2 ≤ (p.1 : ℝ) ^ 2 + (p.2 : ℝ) ^ 2 := by
    unfold radius
    by_cases hle : p.1.natAbs ≤ p.2.natAbs
    · rw [max_eq_right hle]
      exact h2
    · rw [max_eq_left (le_of_not_ge hle)]
      exact h1
  rw [← sq_le_sq₀ (by positivity : 0 ≤ (radius p : ℝ)) (Real.sqrt_nonneg _),
    Real.sq_sqrt hsum]
  exact hsq

private lemma diracMagnitude_tendsto_atTop : Tendsto diracMagnitude cofinite atTop := by
  have hradR : Tendsto (fun p : ℤ × ℤ => (radius p : ℝ)) cofinite atTop :=
    tendsto_natCast_atTop_atTop.comp radius_tendsto_atTop
  have hscale : Tendsto (fun p : ℤ × ℤ => (2 * Real.pi) * (radius p : ℝ)) cofinite atTop :=
    hradR.const_mul_atTop' (by positivity : (0 : ℝ) < 2 * Real.pi)
  refine tendsto_atTop_mono' _ ?_ hscale
  filter_upwards with p
  unfold diracMagnitude
  exact mul_le_mul_of_nonneg_left (radius_le_sqrt p) (by positivity)

private lemma ratio_le_two_inv (x : ℝ) (hx : 0 ≤ x) :
    (1 + x) / (1 + x ^ 2) ≤ 2 / (1 + x) := by
  have hpos1 : 0 < 1 + x := by linarith
  have hpos2 : 0 < 1 + x ^ 2 := by nlinarith [sq_nonneg x]
  rw [div_le_div_iff₀ hpos2 hpos1]
  nlinarith [sq_nonneg (x - 1)]

private lemma norm_resolventBlock_le_two (p : ℤ × ℤ) : ‖resolventBlock p‖ ≤ 2 := by
  calc
    ‖resolventBlock p‖ ≤ (1 + diracMagnitude p) / (1 + diracMagnitude p ^ 2) :=
      norm_resolventBlock_le_bound p
    _ ≤ 2 / (1 + diracMagnitude p) := ratio_le_two_inv _ (diracMagnitude_nonneg p)
    _ ≤ 2 := by
      have hpos : 0 < 1 + diracMagnitude p := by linarith [diracMagnitude_nonneg p]
      rw [div_le_iff₀ hpos]
      nlinarith [diracMagnitude_nonneg p]

private lemma norm_resolventBlock_tendsto_zero :
    Tendsto (fun p : ℤ × ℤ => ‖resolventBlock p‖) cofinite (𝓝 0) := by
  have hden : Tendsto (fun p : ℤ × ℤ => 1 + diracMagnitude p) cofinite atTop := by
    refine tendsto_atTop_mono' _ ?_ diracMagnitude_tendsto_atTop
    filter_upwards with p
    linarith
  have hmajor0 : Tendsto (fun p : ℤ × ℤ => 2 / (1 + diracMagnitude p)) cofinite (𝓝 0) :=
    hden.const_div_atTop 2
  refine squeeze_zero (fun p => norm_nonneg _) ?_ hmajor0
  intro p
  exact (norm_resolventBlock_le_bound p).trans
    (ratio_le_two_inv _ (diracMagnitude_nonneg p))

private noncomputable def resolventDiag : H →L[ℂ] H :=
  lpDiag.diagL (𝕜 := ℂ) (G := fun _ : ℤ × ℤ => Spinor) resolventBlock (C := 2)
    (by norm_num) (fun p => norm_resolventBlock_le_two p)

private lemma isCompactOperator_resolventDiag : IsCompactOperator resolventDiag := by
  exact lpDiag.isCompactOperator_diagL (𝕜 := ℂ) (G := fun _ : ℤ × ℤ => Spinor)
    resolventBlock (C := 2) (by norm_num) (fun p => norm_resolventBlock_le_two p)
    norm_resolventBlock_tendsto_zero

private lemma resolventDiag_mem_diracDomain (x : H) : resolventDiag x ∈ diracDomain := by
  rw [mem_diracDomain_iff]
  have hfun : (fun q => diracBlock q ((resolventDiag x) q)) =
      fun q => (Complex.I • resolventDiag x - x) q := by
    funext q
    rw [resolventDiag, lpDiag.diagL_apply, resolventBlock_dirac_apply]
    rfl
  rw [hfun]
  exact lp.memℓp (Complex.I • resolventDiag x - x)

private lemma resolvent_op_resolventDiag (x : H) :
    (((Complex.I • LinearMap.id (R := ℂ) (M := H)) +ᵥ (-diracDirac) : H →ₗ.[ℂ] H)
      ⟨resolventDiag x, resolventDiag_mem_diracDomain x⟩) = x := by
  refine lp.ext (funext fun q => ?_)
  rw [vadd_apply, LinearMap.smul_apply, LinearMap.id_apply, neg_apply]
  change (Complex.I • resolventDiag x -
      diracDirac ⟨resolventDiag x, resolventDiag_mem_diracDomain x⟩) q = x q
  rw [lp.coeFn_sub, Pi.sub_apply, lp.coeFn_smul, Pi.smul_apply, diracDirac_apply]
  simpa only [resolventDiag, lpDiag.diagL_apply] using resolventBlock_left_inverse q (x q)

set_option maxHeartbeats 800000 in
-- This proof asks Lean to compare the unfolded resolvent operator with a named diagonal map.
private lemma resolvent_eq_resolventDiag :
    diracDirac.resolvent Complex.I = (resolventDiag : H →ₗ[ℂ] H) := by
  rw [LinearPMap.resolvent_apply_eq (f := diracDirac) mem_resolventSet_I]
  apply LinearMap.ext
  intro x
  have h := LinearPMap.apply_inverseAsLinearMap_apply_cancel
      (f := ((Complex.I • LinearMap.id (R := ℂ) (M := H)) +ᵥ (-diracDirac) : H →ₗ.[ℂ] H))
      mem_resolventSet_I
      (⟨resolventDiag x, resolventDiag_mem_diracDomain x⟩ :
        (((Complex.I • LinearMap.id (R := ℂ) (M := H)) +ᵥ (-diracDirac) : H →ₗ.[ℂ] H).domain))
  rw [resolvent_op_resolventDiag] at h
  exact h

/-- The resolvent of the torus Dirac operator at `i` is compact. -/
theorem isCompactOperator_resolvent_I :
    IsCompactOperator (diracDirac.resolvent Complex.I) := by
  rw [resolvent_eq_resolventDiag]
  exact isCompactOperator_resolventDiag

/-! ### The grading `γ = σ₃`

The chirality operator is the block-diagonal operator acting fibrewise by `σ₃ = diag(1, -1)`.
It is a self-adjoint unitary involution (`γ = γ*`, `γ² = 1`) that anticommutes with the Dirac
operator (each Dirac block is off-diagonal, `σ₃` is diagonal, so `σ₃ D₍ₚ₎ = -D₍ₚ₎ σ₃`). -/

/-- The chirality matrix `σ₃ = diag(1, -1)` on the spinor fibre. -/
noncomputable def gradingMatrix : Matrix (Fin 2) (Fin 2) ℂ := !![1, 0; 0, -1]

/-- `σ₃` as an endomorphism of the spinor fibre. -/
noncomputable def gradingBlock : Spinor →ₗ[ℂ] Spinor :=
  Matrix.toEuclideanLin gradingMatrix

/-- `σ₃` as a continuous endomorphism of the spinor fibre. -/
noncomputable def gradingBlockL : Spinor →L[ℂ] Spinor :=
  Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℂ) gradingMatrix

@[simp] theorem coe_gradingBlockL :
    (gradingBlockL : Spinor →ₗ[ℂ] Spinor) = gradingBlock := rfl

@[simp] theorem gradingBlockL_apply (v : Spinor) : gradingBlockL v = gradingBlock v := rfl

private lemma gradingMatrix_mul_self : gradingMatrix * gradingMatrix = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [gradingMatrix, Matrix.mul_apply, Fin.sum_univ_two]

private lemma diracMatrix_mul_gradingMatrix (p : ℤ × ℤ) :
    diracMatrix p * gradingMatrix = -(gradingMatrix * diracMatrix p) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [diracMatrix, gradingMatrix, Matrix.mul_apply, Fin.sum_univ_two, Matrix.neg_apply]

private lemma gradingBlock_isSymmetric : (gradingBlock).IsSymmetric := by
  rw [gradingBlock, Matrix.isSymmetric_toEuclideanLin_iff]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [gradingMatrix, Matrix.conjTranspose_apply]

/-- `σ₃ * σ₃ = 1` as continuous operators (`Matrix.toEuclideanCLM` is a `*`-algebra map). -/
private lemma gradingBlockL_mul_self : gradingBlockL * gradingBlockL = 1 := by
  change Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℂ) gradingMatrix *
      Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℂ) gradingMatrix = 1
  rw [← _root_.map_mul, gradingMatrix_mul_self, _root_.map_one]

private lemma gradingBlock_apply_self (v : Spinor) : gradingBlock (gradingBlock v) = v := by
  have h : gradingBlockL (gradingBlockL v) = (1 : Spinor →L[ℂ] Spinor) v := by
    rw [← ContinuousLinearMap.mul_apply, gradingBlockL_mul_self]
  simpa using h

/-- `D₍ₚ₎ σ₃ = -σ₃ D₍ₚ₎` as continuous operators. -/
private lemma diracBlockL_gradingBlockL_anticomm (p : ℤ × ℤ) :
    diracBlockL p * gradingBlockL = -(gradingBlockL * diracBlockL p) := by
  change Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℂ) (diracMatrix p) *
        Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℂ) gradingMatrix =
      -(Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℂ) gradingMatrix *
        Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℂ) (diracMatrix p))
  rw [← _root_.map_mul, ← _root_.map_mul, diracMatrix_mul_gradingMatrix, _root_.map_neg]

private lemma diracBlock_gradingBlock_anticomm (p : ℤ × ℤ) (v : Spinor) :
    diracBlock p (gradingBlock v) = -gradingBlock (diracBlock p v) := by
  have h := congrArg (fun T : Spinor →L[ℂ] Spinor => T v) (diracBlockL_gradingBlockL_anticomm p)
  simpa [ContinuousLinearMap.mul_apply, ContinuousLinearMap.neg_apply, diracBlockL_apply,
    gradingBlockL_apply] using h

theorem norm_gradingBlockL_le_one : ‖gradingBlockL‖ ≤ 1 := by
  have hdiag : gradingMatrix = Matrix.diagonal ![1, -1] := by
    ext i j
    fin_cases i <;> fin_cases j <;> simp [gradingMatrix, Matrix.diagonal]
  have hnorm : ‖gradingBlockL‖ = ‖(![1, -1] : Fin 2 → ℂ)‖ := by
    change ‖Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℂ) gradingMatrix‖ = _
    rw [Matrix.l2_opNorm_toEuclideanCLM, hdiag, Matrix.l2_opNorm_diagonal]
  rw [hnorm, pi_norm_le_iff_of_nonneg zero_le_one]
  intro i
  fin_cases i <;> simp

/-- The chirality (grading) operator `γ = σ₃` on `ℓ²(ℤ²; ℂ²)`: block-diagonal, acting on each
Fourier mode by `σ₃ = diag(1, -1)`. -/
noncomputable def grading : H →L[ℂ] H :=
  lpDiag.diagL (𝕜 := ℂ) (G := fun _ : ℤ × ℤ => Spinor) (fun _ => gradingBlockL) zero_le_one
    (fun _ => norm_gradingBlockL_le_one)

@[simp] theorem grading_apply (a : H) (q : ℤ × ℤ) : (grading a) q = gradingBlock (a q) := by
  rw [grading, lpDiag.diagL_apply, gradingBlockL_apply]

/-- The grading is symmetric: `⟪γ a, b⟫ = ⟪a, γ b⟫`, fibrewise from `σ₃` being Hermitian. -/
theorem grading_isSymmetric : (grading : H →ₗ[ℂ] H).IsSymmetric := by
  intro a b
  rw [ContinuousLinearMap.coe_coe, lp.inner_eq_tsum, lp.inner_eq_tsum]
  refine tsum_congr fun q => ?_
  rw [grading_apply, grading_apply]
  exact gradingBlock_isSymmetric (a q) (b q)

/-- The grading is self-adjoint. -/
theorem isSelfAdjoint_grading : IsSelfAdjoint grading :=
  ContinuousLinearMap.isSelfAdjoint_iff_isSymmetric.mpr grading_isSymmetric

/-- The grading is an involution: `γ² = 1`. -/
theorem grading_mul_self : grading * grading = 1 := by
  refine ContinuousLinearMap.ext fun a => ?_
  rw [ContinuousLinearMap.one_apply]
  refine lp.ext (funext fun q => ?_)
  rw [ContinuousLinearMap.mul_apply, grading_apply, grading_apply]
  exact gradingBlock_apply_self (a q)

/-- The grading preserves the Dirac domain `H¹`. -/
theorem grading_mem_diracDomain (x : diracDomain) : grading (x : H) ∈ diracDomain := by
  rw [mem_diracDomain_iff]
  have hfun : (fun q => diracBlock q ((grading (x : H)) q))
      = ⇑(-grading (diracDirac x)) := by
    funext q
    rw [grading_apply, diracBlock_gradingBlock_anticomm, lp.coeFn_neg, Pi.neg_apply,
      grading_apply, diracDirac_apply]
  rw [hfun]
  exact lp.memℓp _

/-- The grading anticommutes with the Dirac operator: `D (γ x) = - γ (D x)`. -/
theorem grading_anticomm (x : diracDomain) :
    diracDirac ⟨grading (x : H), grading_mem_diracDomain x⟩ = -grading (diracDirac x) := by
  refine lp.ext (funext fun q => ?_)
  rw [diracDirac_apply, lp.coeFn_neg, Pi.neg_apply, grading_apply, grading_apply,
    diracDirac_apply, diracBlock_gradingBlock_anticomm]

/-! ### The shift representation of the torus algebra -/

/-- Reindexing an `ℓ²(ℤ²; ℂ²)` vector by right addition preserves square-summability. -/
theorem shift_memℓp (g : ℤ × ℤ) (ψ : H) :
    Memℓp (fun p : ℤ × ℤ => ψ (p + g)) 2 := by
  rw [memℓp_gen_iff (by norm_num : 0 < (2 : ℝ≥0∞).toReal)]
  have hψ : Summable (fun p : ℤ × ℤ => ‖ψ p‖ ^ (2 : ℝ≥0∞).toReal) :=
    (lp.memℓp ψ).summable (by norm_num : 0 < (2 : ℝ≥0∞).toReal)
  simpa [Function.comp_def] using ((Equiv.addRight g).summable_iff).mpr hψ

/-- The right-translation shift `(shiftFun g ψ)ₚ = ψ₍ₚ₊g₎` on Fourier coefficients. -/
noncomputable def shiftFun (g : ℤ × ℤ) (ψ : H) : H :=
  ⟨fun p : ℤ × ℤ => ψ (p + g), shift_memℓp g ψ⟩

@[simp] theorem shiftFun_apply (g : ℤ × ℤ) (ψ : H) (p : ℤ × ℤ) :
    (shiftFun g ψ) p = ψ (p + g) := rfl

/-- The shift is norm-preserving. -/
theorem norm_shiftFun (g : ℤ × ℤ) (ψ : H) : ‖shiftFun g ψ‖ = ‖ψ‖ := by
  have hp : 0 < (2 : ℝ≥0∞).toReal := by norm_num
  have hpow :
      ‖shiftFun g ψ‖ ^ (2 : ℝ≥0∞).toReal = ‖ψ‖ ^ (2 : ℝ≥0∞).toReal := by
    rw [lp.norm_rpow_eq_tsum hp, lp.norm_rpow_eq_tsum hp]
    exact (Equiv.addRight g).tsum_eq
      (fun q : ℤ × ℤ => ‖ψ q‖ ^ (2 : ℝ≥0∞).toReal)
  norm_num at hpow
  exact hpow

/-- The unitary shift of `H = ℓ²(ℤ²; ℂ²)` by a lattice vector. -/
noncomputable def shiftEquiv (g : ℤ × ℤ) : H ≃ₗᵢ[ℂ] H where
  toFun := shiftFun g
  invFun := shiftFun (-g)
  left_inv := by
    intro ψ
    refine lp.ext (funext fun p => ?_)
    simp [shiftFun_apply, add_assoc]
  right_inv := by
    intro ψ
    refine lp.ext (funext fun p => ?_)
    simp [shiftFun_apply, add_assoc]
  map_add' := by
    intro ψ φ
    refine lp.ext (funext fun p => ?_)
    simp only [shiftFun_apply, lp.coeFn_add, Pi.add_apply]
  map_smul' := by
    intro c ψ
    refine lp.ext (funext fun p => ?_)
    simp only [shiftFun_apply, lp.coeFn_smul, Pi.smul_apply, RingHom.id_apply]
  norm_map' := norm_shiftFun g

/-- The Fourier shift unitary `(W g ψ)ₚ = ψ₍ₚ₊g₎`. These two generators represent the
coordinate functions of the torus algebra on the Fourier side. -/
noncomputable def W (g : ℤ × ℤ) : H →L[ℂ] H :=
  (shiftEquiv g : H →L[ℂ] H)

@[simp] theorem W_apply (g : ℤ × ℤ) (ψ : H) (p : ℤ × ℤ) :
    (W g ψ) p = ψ (p + g) := rfl

theorem W_zero : W 0 = 1 := by
  refine ContinuousLinearMap.ext fun ψ => ?_
  refine lp.ext (funext fun p => ?_)
  simp [W_apply]

theorem W_mul (g₁ g₂ : ℤ × ℤ) : W g₁ * W g₂ = W (g₁ + g₂) := by
  refine ContinuousLinearMap.ext fun ψ => ?_
  refine lp.ext (funext fun p => ?_)
  simp [W_apply, ContinuousLinearMap.mul_apply, add_assoc]

theorem W_star (g : ℤ × ℤ) : star (W g) = W (-g) := by
  have hsymm : (shiftEquiv g).symm = shiftEquiv (-g) := by
    refine LinearIsometryEquiv.ext fun ψ => ?_
    rfl
  unfold W
  rw [LinearIsometryEquiv.star_eq_symm, hsymm]

private lemma diracMatrix_add (p g : ℤ × ℤ) :
    diracMatrix (p + g) = diracMatrix p + diracMatrix g := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [diracMatrix, Matrix.add_apply, Matrix.smul_apply, Prod.fst_add, Prod.snd_add]
    <;> ring

private lemma diracBlock_add_apply (p g : ℤ × ℤ) (v : Spinor) :
    diracBlock (p + g) v = diracBlock p v + diracBlock g v := by
  have h :
      diracBlockL (p + g) = diracBlockL p + diracBlockL g := by
    change Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℂ) (diracMatrix (p + g)) =
      Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℂ) (diracMatrix p) +
        Matrix.toEuclideanCLM (n := Fin 2) (𝕜 := ℂ) (diracMatrix g)
    rw [diracMatrix_add, _root_.map_add]
  have hv := congrArg (fun T : Spinor →L[ℂ] Spinor => T v) h
  simpa [ContinuousLinearMap.add_apply, diracBlockL_apply] using hv

private noncomputable def commutatorDiag (g : ℤ × ℤ) : H →L[ℂ] H :=
  lpDiag.diagL (𝕜 := ℂ) (G := fun _ : ℤ × ℤ => Spinor) (fun _ => diracBlockL g)
    (norm_nonneg _) (fun _ => le_rfl)

@[simp] private lemma commutatorDiag_apply (g : ℤ × ℤ) (ψ : H) (p : ℤ × ℤ) :
    (commutatorDiag g ψ) p = diracBlock g (ψ p) := by
  rw [commutatorDiag, lpDiag.diagL_apply, diracBlockL_apply]

private theorem W_mem_diracDomain (g : ℤ × ℤ) {x : H} (hx : x ∈ diracDomain) :
    W g x ∈ diracDomain := by
  rw [mem_diracDomain_iff]
  let xd : diracDomain := ⟨x, hx⟩
  have hfun : (fun q : ℤ × ℤ => diracBlock q ((W g x) q)) =
      fun q : ℤ × ℤ => (W g (diracDirac xd) - commutatorDiag g (W g x)) q := by
    funext q
    rw [W_apply, lp.coeFn_sub, Pi.sub_apply, W_apply, diracDirac_apply,
      commutatorDiag_apply, W_apply]
    have h := diracBlock_add_apply q g (x (q + g))
    rw [h]
    abel
  rw [hfun]
  exact lp.memℓp _

private theorem W_commutator (g : ℤ × ℤ) (x : diracDomain) :
    W g (diracDirac x) -
        diracDirac ⟨W g (x : H), W_mem_diracDomain g x.2⟩ =
      commutatorDiag g (W g (x : H)) := by
  refine lp.ext (funext fun p => ?_)
  rw [lp.coeFn_sub, Pi.sub_apply, W_apply, diracDirac_apply, diracDirac_apply,
    commutatorDiag_apply, W_apply]
  have h := diracBlock_add_apply p g ((x : H) (p + g))
  rw [h]
  abel

private def MapsDom (T : H →L[ℂ] H) : Prop :=
  ∀ x : H, x ∈ diracDomain → T x ∈ diracDomain

private def CommBdd (T : H →L[ℂ] H) (hT : MapsDom T) : Prop :=
  ∃ B : H →L[ℂ] H, ∀ x : diracDomain,
    T (diracDirac x) - diracDirac ⟨T (x : H), hT (x : H) x.2⟩ = B (x : H)

private def Smooth (T : H →L[ℂ] H) : Prop :=
  ∃ hT : MapsDom T, CommBdd T hT

private def Smooth' (T : H →L[ℂ] H) : Prop :=
  Smooth T ∧ Smooth (star T)

private theorem smooth_algebraMap (c : ℂ) :
    Smooth (algebraMap ℂ (H →L[ℂ] H) c) := by
  let T : H →L[ℂ] H := algebraMap ℂ (H →L[ℂ] H) c
  have hT : MapsDom T := by
    intro x hx
    simpa [T, ContinuousLinearMap.algebraMap_apply] using diracDomain.smul_mem c hx
  refine ⟨hT, 0, fun x => ?_⟩
  rw [ContinuousLinearMap.zero_apply]
  change c • diracDirac x - diracDirac (c • x) = 0
  rw [show diracDirac (c • x) = c • diracDirac x from diracDirac.map_smul c x, sub_self]

private theorem smooth'_algebraMap (c : ℂ) :
    Smooth' (algebraMap ℂ (H →L[ℂ] H) c) := by
  refine ⟨smooth_algebraMap c, ?_⟩
  simpa [← algebraMap_star_comm (A := H →L[ℂ] H) c] using smooth_algebraMap (star c)

private theorem smooth_add {S T : H →L[ℂ] H} (hS : Smooth S) (hT : Smooth T) :
    Smooth (S + T) := by
  rcases hS with ⟨hSdom, BS, hBS⟩
  rcases hT with ⟨hTdom, BT, hBT⟩
  have hdom : MapsDom (S + T) := by
    intro x hx
    simpa [ContinuousLinearMap.add_apply] using diracDomain.add_mem (hSdom x hx) (hTdom x hx)
  refine ⟨hdom, BS + BT, fun x => ?_⟩
  have hSx : S (x : H) ∈ diracDomain := hSdom (x : H) x.2
  have hTx : T (x : H) ∈ diracDomain := hTdom (x : H) x.2
  have hDadd :
      diracDirac ⟨(S + T) (x : H), hdom (x : H) x.2⟩ =
        diracDirac (⟨S (x : H), hSx⟩ + ⟨T (x : H), hTx⟩ : diracDomain) := by
    congr 1
  rw [ContinuousLinearMap.add_apply, hDadd]
  rw [show diracDirac (⟨S (x : H), hSx⟩ + ⟨T (x : H), hTx⟩ : diracDomain) =
      diracDirac ⟨S (x : H), hSx⟩ + diracDirac ⟨T (x : H), hTx⟩ from
        diracDirac.map_add _ _]
  rw [ContinuousLinearMap.add_apply, ← hBS x, ← hBT x]
  abel

private theorem smooth'_add {S T : H →L[ℂ] H} (hS : Smooth' S) (hT : Smooth' T) :
    Smooth' (S + T) := by
  refine ⟨smooth_add hS.1 hT.1, ?_⟩
  simpa [star_add] using smooth_add hS.2 hT.2

private theorem smooth_mul {S T : H →L[ℂ] H} (hS : Smooth S) (hT : Smooth T) :
    Smooth (S * T) := by
  rcases hS with ⟨hSdom, BS, hBS⟩
  rcases hT with ⟨hTdom, BT, hBT⟩
  have hdom : MapsDom (S * T) := by
    intro x hx
    simpa [ContinuousLinearMap.mul_apply] using hSdom (T x) (hTdom x hx)
  refine ⟨hdom, S.comp BT + BS.comp T, fun x => ?_⟩
  let y : diracDomain := ⟨T (x : H), hTdom (x : H) x.2⟩
  have hBTy : T (diracDirac x) - diracDirac y = BT (x : H) := by
    simpa [y] using hBT x
  have hD :
      diracDirac ⟨(S * T) (x : H), hdom (x : H) x.2⟩ =
        diracDirac ⟨S (y : H), hSdom (y : H) y.2⟩ := by
    congr 1
  rw [ContinuousLinearMap.mul_apply, hD]
  rw [ContinuousLinearMap.add_apply, ContinuousLinearMap.comp_apply,
    ContinuousLinearMap.comp_apply]
  calc
    S (T (diracDirac x)) - diracDirac ⟨S (y : H), hSdom (y : H) y.2⟩
        = S (T (diracDirac x)) - S (diracDirac y) +
            (S (diracDirac y) - diracDirac ⟨S (y : H), hSdom (y : H) y.2⟩) := by
          abel
    _ = S (T (diracDirac x) - diracDirac y) +
            (S (diracDirac y) - diracDirac ⟨S (y : H), hSdom (y : H) y.2⟩) := by
          rw [_root_.map_sub]
    _ = S (BT (x : H)) + BS (y : H) := by rw [hBTy, hBS y]
    _ = S (BT (x : H)) + BS (T (x : H)) := by rfl

private theorem smooth'_mul {S T : H →L[ℂ] H} (hS : Smooth' S) (hT : Smooth' T) :
    Smooth' (S * T) := by
  refine ⟨smooth_mul hS.1 hT.1, ?_⟩
  simpa [star_mul] using smooth_mul hT.2 hS.2

private theorem smooth'_star {T : H →L[ℂ] H} (hT : Smooth' T) : Smooth' (star T) := by
  refine ⟨hT.2, ?_⟩
  simpa using hT.1

private theorem smooth_W (g : ℤ × ℤ) : Smooth (W g) := by
  have hdom : MapsDom (W g) := by
    intro x hx
    exact W_mem_diracDomain g hx
  refine ⟨hdom, (commutatorDiag g).comp (W g), fun x => ?_⟩
  simpa [ContinuousLinearMap.comp_apply] using W_commutator g x

private theorem smooth'_W (g : ℤ × ℤ) : Smooth' (W g) := by
  refine ⟨smooth_W g, ?_⟩
  rw [W_star]
  exact smooth_W (-g)

/-- The star-subalgebra of bounded operators generated by the two coordinate shift unitaries
of the Fourier representation of the two-torus. -/
noncomputable def algebra : StarSubalgebra ℂ (H →L[ℂ] H) :=
  StarAlgebra.adjoin ℂ ({W (1, 0), W (0, 1)} : Set (H →L[ℂ] H))

/-- The faithful representation of the generated torus algebra by inclusion into bounded
operators on `H`. -/
noncomputable def rep : algebra →⋆ₐ[ℂ] (H →L[ℂ] H) :=
  algebra.subtype

private theorem smooth'_algebra (a : algebra) : Smooth' (a : H →L[ℂ] H) := by
  exact StarAlgebra.adjoin_induction_subtype
    (s := ({W (1, 0), W (0, 1)} : Set (H →L[ℂ] H)))
    (p := fun a : algebra => Smooth' (a : H →L[ℂ] H)) a
    (fun x hx => by
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
      rcases hx with rfl | rfl
      · exact smooth'_W (1, 0)
      · exact smooth'_W (0, 1))
    (fun c => by simpa using smooth'_algebraMap c)
    (fun _ _ hx hy => by simpa using smooth'_add hx hy)
    (fun _ _ hx hy => by simpa using smooth'_mul hx hy)
    (fun _ hx => by simpa using smooth'_star hx)

private theorem rep_maps_diracDomain (a : algebra) (x : diracDomain) :
    rep a (x : H) ∈ diracDomain := by
  rcases (smooth'_algebra a).1 with ⟨hdom, _⟩
  exact hdom (x : H) x.2

private theorem odd_comm_bound (a : algebra) :
    (iSup fun (x : Metric.closedBall (0 : diracDirac.domain) 1) ↦
      ‖(rep a) (diracDirac (x : diracDirac.domain)) -
        (diracDirac ⟨(rep a) (x : diracDirac.domain),
          rep_maps_diracDomain a (x : diracDirac.domain)⟩)‖ₑ) < ∞ := by
  rcases (smooth'_algebra a).1 with ⟨hdom, B, hB⟩
  refine lt_of_le_of_lt (iSup_le fun x => ?_) (enorm_lt_top (x := B))
  let y : diracDomain := (x : diracDirac.domain)
  have hnorm : ‖(y : H)‖ ≤ 1 := by
    have hx' : dist (x : diracDirac.domain) 0 ≤ 1 := x.2
    simpa [dist_eq_norm, y] using hx'
  have hnorme : ‖(y : H)‖ₑ ≤ (1 : ℝ≥0∞) := by
    rw [← ofReal_norm, ← ENNReal.ofReal_one]
    exact ENNReal.ofReal_le_ofReal hnorm
  have hD :
      diracDirac ⟨(rep a) (y : H), rep_maps_diracDomain a y⟩ =
        diracDirac ⟨(rep a) (y : H), hdom (y : H) y.2⟩ := by
    congr 1
  calc
    ‖(rep a) (diracDirac y) -
        diracDirac ⟨(rep a) (y : H), rep_maps_diracDomain a y⟩‖ₑ
        = ‖B (y : H)‖ₑ := by
          rw [hD]
          simpa [rep] using congrArg (fun z : H => ‖z‖ₑ) (hB y)
    _ ≤ ‖B‖ₑ := by
      calc
        ‖B (y : H)‖ₑ ≤ ‖B‖ₑ * ‖(y : H)‖ₑ := B.le_opNorm_enorm _
        _ ≤ ‖B‖ₑ * 1 := by
          simpa [mul_comm] using mul_le_mul_left (a := ‖B‖ₑ) hnorme
        _ = ‖B‖ₑ := by rw [mul_one]

/-- The generated torus representation, together with the torus Dirac operator, is an odd
spectral triple. -/
theorem isOddSpectralTriple : IsOddSpectralTriple algebra diracDirac rep where
  self_adjoint := diracDirac_isSelfAdjoint
  dom_comp := rep_maps_diracDomain
  comm := odd_comm_bound

private theorem grading_comm_W (g : ℤ × ℤ) :
    grading.comp (W g) = (W g).comp grading := by
  refine ContinuousLinearMap.ext fun ψ => ?_
  refine lp.ext (funext fun p => ?_)
  rw [ContinuousLinearMap.comp_apply, ContinuousLinearMap.comp_apply, grading_apply,
    W_apply, W_apply, grading_apply]

private theorem grading_comm_algebra (a : algebra) :
    grading.comp (rep a) = (rep a).comp grading := by
  change grading * (a : H →L[ℂ] H) = (a : H →L[ℂ] H) * grading
  exact StarAlgebra.adjoin_induction_subtype
    (s := ({W (1, 0), W (0, 1)} : Set (H →L[ℂ] H)))
    (p := fun a : algebra => grading * (a : H →L[ℂ] H) = (a : H →L[ℂ] H) * grading) a
    (fun x hx => by
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
      rcases hx with rfl | rfl
      · exact grading_comm_W (1, 0)
      · exact grading_comm_W (0, 1))
    (fun c => by
      change grading * algebraMap ℂ (H →L[ℂ] H) c =
        algebraMap ℂ (H →L[ℂ] H) c * grading
      exact (Algebra.commutes c grading).symm)
    (fun x y hx hy => by
      change grading * ((x : H →L[ℂ] H) + (y : H →L[ℂ] H)) =
        ((x : H →L[ℂ] H) + (y : H →L[ℂ] H)) * grading
      rw [mul_add, add_mul, hx, hy])
    (fun x y hx hy => by
      change grading * ((x : H →L[ℂ] H) * (y : H →L[ℂ] H)) =
        ((x : H →L[ℂ] H) * (y : H →L[ℂ] H)) * grading
      calc
        grading * ((x : H →L[ℂ] H) * (y : H →L[ℂ] H))
            = (grading * (x : H →L[ℂ] H)) * (y : H →L[ℂ] H) := by
              rw [mul_assoc]
        _ = ((x : H →L[ℂ] H) * grading) * (y : H →L[ℂ] H) := by
              rw [hx]
        _ = (x : H →L[ℂ] H) * (grading * (y : H →L[ℂ] H)) := by
              rw [mul_assoc]
        _ = (x : H →L[ℂ] H) * ((y : H →L[ℂ] H) * grading) := by
              rw [hy]
        _ = ((x : H →L[ℂ] H) * (y : H →L[ℂ] H)) * grading := by
              rw [← mul_assoc])
    (fun x hx => by
      change grading * star (x : H →L[ℂ] H) = star (x : H →L[ℂ] H) * grading
      have hs := congrArg star hx
      rw [star_mul, star_mul, isSelfAdjoint_grading.star_eq] at hs
      exact hs.symm)

/-- The torus spectral triple is even for the chirality grading `γ = σ₃`. -/
theorem isEvenSpectralTriple : IsEvenSpectralTriple algebra diracDirac rep grading where
  toIsOddSpectralTriple := isOddSpectralTriple
  self_adjoint_grading := isSelfAdjoint_grading
  grading_sq := grading_mul_self
  grading_comm := grading_comm_algebra
  grading_dom := grading_mem_diracDomain
  grading_anticomm := grading_anticomm

/-- The torus spectral triple has compact resolvent at `i`, hence is finitely summable in the
basic compact-resolvent sense used in this development. -/
theorem isFinitelySummableSpectralTriple :
    IsFinitelySummableSpectralTriple algebra diracDirac rep :=
  isOddSpectralTriple.toIsFinitelySummableSpectralTriple (by simp) isCompactOperator_resolvent_I

/-- The zero Fourier-mode Dirac block vanishes. -/
private lemma diracBlock_zero : diracBlock (0 : ℤ × ℤ) = 0 := by
  ext v i
  fin_cases i <;> simp [diracBlock, Matrix.toEuclideanLin, Matrix.toLpLin_apply]

private lemma sum_sq_pos_of_prod_ne_zero {p : ℤ × ℤ} (hp : p ≠ 0) :
    0 < (p.1 : ℝ) ^ 2 + (p.2 : ℝ) ^ 2 := by
  have hnonneg : 0 ≤ (p.1 : ℝ) ^ 2 + (p.2 : ℝ) ^ 2 := by positivity
  refine lt_of_le_of_ne hnonneg ?_
  intro hzero
  have hsumzero : (p.1 : ℝ) ^ 2 + (p.2 : ℝ) ^ 2 = 0 := hzero.symm
  have hp1sq : (p.1 : ℝ) ^ 2 = 0 := by nlinarith [sq_nonneg (p.2 : ℝ)]
  have hp2sq : (p.2 : ℝ) ^ 2 = 0 := by nlinarith [sq_nonneg (p.1 : ℝ)]
  have hp1 : p.1 = 0 := by exact_mod_cast (sq_eq_zero_iff.mp hp1sq)
  have hp2 : p.2 = 0 := by exact_mod_cast (sq_eq_zero_iff.mp hp2sq)
  exact hp (Prod.ext hp1 hp2)

private lemma diracMagnitude_ne_zero {p : ℤ × ℤ} (hp : p ≠ 0) :
    diracMagnitude p ≠ 0 := by
  have hsum : 0 < (p.1 : ℝ) ^ 2 + (p.2 : ℝ) ^ 2 :=
    sum_sq_pos_of_prod_ne_zero hp
  have hsqrt : 0 < Real.sqrt ((p.1 : ℝ) ^ 2 + (p.2 : ℝ) ^ 2) :=
    Real.sqrt_pos.2 hsum
  have hscale : 0 < 2 * Real.pi := by positivity
  unfold diracMagnitude
  exact ne_of_gt (mul_pos hscale hsqrt)

/-- Away from the zero Fourier mode, the Dirac block is injective. -/
private lemma diracBlock_injective {p : ℤ × ℤ} (hp : p ≠ 0) :
    Function.Injective (diracBlock p) := by
  rw [← LinearMap.ker_eq_bot, LinearMap.ker_eq_bot']
  intro v hv
  have hsq := diracBlock_sq_apply p v
  rw [hv, _root_.map_zero] at hsq
  have hscalar : (((diracMagnitude p ^ 2 : ℝ) : ℂ)) ≠ 0 := by
    exact_mod_cast (pow_ne_zero 2 (diracMagnitude_ne_zero hp))
  exact (smul_eq_zero.mp hsq.symm).resolve_left hscalar

/-- The kernel of the torus Dirac operator consists exactly of vectors supported at the
zero Fourier mode. -/
private lemma mem_Dkernel_diracDirac_iff {x : H} :
    x ∈ Dkernel diracDirac ↔ ∀ p : ℤ × ℤ, p ≠ 0 → x p = 0 := by
  constructor
  · intro hx p hp
    rw [mem_Dkernel_iff] at hx
    obtain ⟨hxdom, hxzero⟩ := hx
    have hcoord := congrArg (fun y : H => y p) hxzero
    apply diracBlock_injective hp
    simpa [diracDirac_apply] using hcoord
  · intro hsupp
    rw [mem_Dkernel_iff]
    have hxdom : x ∈ diracDomain := by
      rw [mem_diracDomain_iff]
      have hfun : (fun p : ℤ × ℤ => diracBlock p (x p)) = 0 := by
        funext p
        change diracBlock p (x p) = (0 : Spinor)
        by_cases hp : p = 0
        · subst p
          rw [diracBlock_zero, LinearMap.zero_apply]
        · rw [hsupp p hp, _root_.map_zero]
      rw [hfun]
      exact zero_memℓp
    refine ⟨hxdom, ?_⟩
    refine lp.ext (funext fun p => ?_)
    change (diracDirac ⟨x, hxdom⟩) p = (0 : Spinor)
    by_cases hp : p = 0
    · subst p
      simp [diracDirac_apply, diracBlock_zero]
    · simp [diracDirac_apply, hsupp p hp]

private noncomputable def spinorPlus : Spinor :=
  EuclideanSpace.single (0 : Fin 2) (1 : ℂ)

private noncomputable def spinorMinus : Spinor :=
  EuclideanSpace.single (1 : Fin 2) (1 : ℂ)

private noncomputable def plusKernelVector : H :=
  lp.single 2 (0 : ℤ × ℤ) spinorPlus

private noncomputable def minusKernelVector : H :=
  lp.single 2 (0 : ℤ × ℤ) spinorMinus

private lemma gradingBlock_apply_zero (v : Spinor) :
    (gradingBlock v) (0 : Fin 2) = v (0 : Fin 2) := by
  simp [gradingBlock, gradingMatrix, Matrix.toEuclideanLin, Matrix.toLpLin_apply,
    Matrix.vecHead]

private lemma gradingBlock_apply_one (v : Spinor) :
    (gradingBlock v) (1 : Fin 2) = -v (1 : Fin 2) := by
  simp [gradingBlock, gradingMatrix, Matrix.toEuclideanLin, Matrix.toLpLin_apply,
    Matrix.vecHead, Matrix.vecTail]

private lemma gradingBlock_single_plus :
    gradingBlock spinorPlus = spinorPlus := by
  ext i
  fin_cases i <;> simp [spinorPlus, gradingBlock, gradingMatrix, Matrix.toEuclideanLin,
    Matrix.toLpLin_apply]

private lemma gradingBlock_single_minus :
    gradingBlock spinorMinus = (-1 : ℂ) • spinorMinus := by
  ext i
  fin_cases i <;> simp [spinorMinus, gradingBlock, gradingMatrix, Matrix.toEuclideanLin,
    Matrix.toLpLin_apply]

private lemma spinor_eq_plus_smul {v : Spinor} (hv : gradingBlock v = v) :
    v = (v (0 : Fin 2)) • spinorPlus := by
  ext i
  fin_cases i
  · simp [spinorPlus]
  · have h1 := congrArg (fun w : Spinor => w (1 : Fin 2)) hv
    have hv1 : v (1 : Fin 2) = 0 := by
      simpa [gradingBlock, gradingMatrix, Matrix.toEuclideanLin, Matrix.toLpLin_apply,
        Matrix.vecHead, Matrix.vecTail, CharZero.neg_eq_self_iff] using h1
    simp [spinorPlus, hv1]

private lemma spinor_eq_minus_smul {v : Spinor} (hv : gradingBlock v = (-1 : ℂ) • v) :
    v = (v (1 : Fin 2)) • spinorMinus := by
  ext i
  fin_cases i
  · have h0 := congrArg (fun w : Spinor => w (0 : Fin 2)) hv
    have hv0 : v (0 : Fin 2) = 0 := by
      simpa [gradingBlock, gradingMatrix, Matrix.toEuclideanLin, Matrix.toLpLin_apply,
        Matrix.vecHead, CharZero.eq_neg_self_iff] using h0
    simp [spinorMinus, hv0]
  · simp [spinorMinus]

private lemma plusKernelVector_ne_zero : plusKernelVector ≠ 0 := by
  intro h
  have hmode := congrArg (fun x : H => x (0 : ℤ × ℤ)) h
  have hspin : spinorPlus = 0 := by
    simpa [plusKernelVector] using hmode
  have hcoord := congrArg (fun v : Spinor => v (0 : Fin 2)) hspin
  norm_num [spinorPlus] at hcoord

private lemma minusKernelVector_ne_zero : minusKernelVector ≠ 0 := by
  intro h
  have hmode := congrArg (fun x : H => x (0 : ℤ × ℤ)) h
  have hspin : spinorMinus = 0 := by
    simpa [minusKernelVector] using hmode
  have hcoord := congrArg (fun v : Spinor => v (1 : Fin 2)) hspin
  norm_num [spinorMinus] at hcoord

private lemma plusKernelVector_apply_zero :
    plusKernelVector (0 : ℤ × ℤ) = spinorPlus := by
  change (lp.single 2 (0 : ℤ × ℤ) spinorPlus : H) (0 : ℤ × ℤ) = spinorPlus
  exact lp.single_apply_self (E := fun _ : ℤ × ℤ => Spinor) 2 (0 : ℤ × ℤ) spinorPlus

private lemma plusKernelVector_apply_ne {p : ℤ × ℤ} (hp : p ≠ 0) :
    plusKernelVector p = 0 := by
  change (lp.single 2 (0 : ℤ × ℤ) spinorPlus : H) p = 0
  exact lp.single_apply_ne (E := fun _ : ℤ × ℤ => Spinor) 2 (0 : ℤ × ℤ) spinorPlus hp

private lemma minusKernelVector_apply_zero :
    minusKernelVector (0 : ℤ × ℤ) = spinorMinus := by
  change (lp.single 2 (0 : ℤ × ℤ) spinorMinus : H) (0 : ℤ × ℤ) = spinorMinus
  exact lp.single_apply_self (E := fun _ : ℤ × ℤ => Spinor) 2 (0 : ℤ × ℤ) spinorMinus

private lemma minusKernelVector_apply_ne {p : ℤ × ℤ} (hp : p ≠ 0) :
    minusKernelVector p = 0 := by
  change (lp.single 2 (0 : ℤ × ℤ) spinorMinus : H) p = 0
  exact lp.single_apply_ne (E := fun _ : ℤ × ℤ => Spinor) 2 (0 : ℤ × ℤ) spinorMinus hp

/-- The `+1` graded part of the Dirac kernel is the zero-mode upper spinor line. -/
private lemma positive_gradedKernel_eq_span :
    Dkernel diracDirac ⊓ Module.End.eigenspace (grading : Module.End ℂ H) (1 : ℂ) =
      ℂ ∙ plusKernelVector := by
  apply le_antisymm
  · intro x hx
    rw [Submodule.mem_span_singleton]
    refine ⟨x (0 : ℤ × ℤ) (0 : Fin 2), ?_⟩
    refine lp.ext (funext fun p => ?_)
    by_cases hp : p = 0
    · subst p
      have heig : grading (x : H) = (1 : ℂ) • x :=
        Module.End.mem_eigenspace_iff.mp hx.2
      have hfibre :
          x (0 : ℤ × ℤ) =
            (x (0 : ℤ × ℤ) (0 : Fin 2)) • spinorPlus := by
        apply spinor_eq_plus_smul
        have hmode := congrArg (fun y : H => y (0 : ℤ × ℤ)) heig
        simpa [grading_apply] using hmode
      simp only [lp.coeFn_smul, Pi.smul_apply, plusKernelVector_apply_zero]
      exact hfibre.symm
    · have hsupp := (mem_Dkernel_diracDirac_iff.mp hx.1) p hp
      simp only [lp.coeFn_smul, Pi.smul_apply, plusKernelVector_apply_ne hp, smul_zero]
      exact hsupp.symm
  · intro x hx
    rw [Submodule.mem_span_singleton] at hx
    obtain ⟨c, rfl⟩ := hx
    refine ⟨?_, ?_⟩
    · exact mem_Dkernel_diracDirac_iff.mpr fun p hp => by
        simp only [lp.coeFn_smul, Pi.smul_apply, plusKernelVector_apply_ne hp, smul_zero]
    · apply Module.End.mem_eigenspace_iff.mpr
      change grading (c • plusKernelVector) = (1 : ℂ) • (c • plusKernelVector)
      refine lp.ext (funext fun p => ?_)
      by_cases hp : p = 0
      · subst p
        simp only [grading_apply, lp.coeFn_smul, Pi.smul_apply, plusKernelVector_apply_zero,
          _root_.map_smul, gradingBlock_single_plus, one_smul]
      · simp only [grading_apply, lp.coeFn_smul, Pi.smul_apply, plusKernelVector_apply_ne hp,
          smul_zero, _root_.map_zero, one_smul]

/-- The `-1` graded part of the Dirac kernel is the zero-mode lower spinor line. -/
private lemma negative_gradedKernel_eq_span :
    Dkernel diracDirac ⊓ Module.End.eigenspace (grading : Module.End ℂ H) (-1 : ℂ) =
      ℂ ∙ minusKernelVector := by
  apply le_antisymm
  · intro x hx
    rw [Submodule.mem_span_singleton]
    refine ⟨x (0 : ℤ × ℤ) (1 : Fin 2), ?_⟩
    refine lp.ext (funext fun p => ?_)
    by_cases hp : p = 0
    · subst p
      have heig : grading (x : H) = (-1 : ℂ) • x :=
        Module.End.mem_eigenspace_iff.mp hx.2
      have hfibre :
          x (0 : ℤ × ℤ) =
            (x (0 : ℤ × ℤ) (1 : Fin 2)) • spinorMinus := by
        apply spinor_eq_minus_smul
        have hmode := congrArg (fun y : H => y (0 : ℤ × ℤ)) heig
        simpa [grading_apply] using hmode
      simp only [lp.coeFn_smul, Pi.smul_apply, minusKernelVector_apply_zero]
      exact hfibre.symm
    · have hsupp := (mem_Dkernel_diracDirac_iff.mp hx.1) p hp
      simp only [lp.coeFn_smul, Pi.smul_apply, minusKernelVector_apply_ne hp, smul_zero]
      exact hsupp.symm
  · intro x hx
    rw [Submodule.mem_span_singleton] at hx
    obtain ⟨c, rfl⟩ := hx
    refine ⟨?_, ?_⟩
    · exact mem_Dkernel_diracDirac_iff.mpr fun p hp => by
        simp only [lp.coeFn_smul, Pi.smul_apply, minusKernelVector_apply_ne hp, smul_zero]
    · apply Module.End.mem_eigenspace_iff.mpr
      change grading (c • minusKernelVector) = (-1 : ℂ) • (c • minusKernelVector)
      refine lp.ext (funext fun p => ?_)
      by_cases hp : p = 0
      · subst p
        change grading (c • minusKernelVector) (0 : ℤ × ℤ) =
          ((-1 : ℂ) • (c • minusKernelVector)) (0 : ℤ × ℤ)
        simp only [grading_apply, lp.coeFn_smul, Pi.smul_apply, minusKernelVector_apply_zero,
          _root_.map_smul, gradingBlock_single_minus, smul_smul]
        rw [mul_comm]
      · simp only [grading_apply, lp.coeFn_smul, Pi.smul_apply, minusKernelVector_apply_ne hp,
          smul_zero, _root_.map_zero]

private lemma finrank_positive_gradedKernel :
    Module.finrank ℂ ↥(Dkernel diracDirac ⊓
      Module.End.eigenspace (grading : Module.End ℂ H) (1 : ℂ)) = 1 := by
  rw [positive_gradedKernel_eq_span]
  exact finrank_span_singleton plusKernelVector_ne_zero

private lemma finrank_negative_gradedKernel :
    Module.finrank ℂ ↥(Dkernel diracDirac ⊓
      Module.End.eigenspace (grading : Module.End ℂ H) (-1 : ℂ)) = 1 := by
  rw [negative_gradedKernel_eq_span]
  exact finrank_span_singleton minusKernelVector_ne_zero

/-- The flat Dirac spectral triple on the two-torus has vanishing graded kernel index. -/
theorem index_eq_zero : isEvenSpectralTriple.index = 0 := by
  change SpectralTriples.index diracDirac grading = 0
  unfold SpectralTriples.index
  rw [finrank_positive_gradedKernel, finrank_negative_gradedKernel]
  norm_num

end SpectralTriples.Torus
